// File generated by Gambit v4.9.4
// Link info: (409004 (js ((compactness 9))) "limina" (("limina")) (module_register entrypt_init returnpt_init ctrlpt_init parententrypt_init scm2host host2scm flonumbox peps build_rest make_interned_keyword r3 r4 closure_alloc r2 ffi check_procedure make_interned_symbol glo check_procedure_glo poll box string base92_decode r1 r0 sp stack wrong_nargs nargs) (mutex-lock! %%object-keys srfi/1#list thread-sleep! entries mutex-unlock! lim r gen-layers srfi/1#null? *limina-revision* ##host-function-memoized srfi/69#alist->hash-table srfi/1#map |[...]| hacky-thread srfi/1#car srfi/1#cons %object->alist srfi/1#cadr later setAttribute mat wireframe make-mutex sogltf) (%%object-keys lim *limina-revision* %object->alist wireframe sogltf) (%%object-keys lim *limina-revision* %object->alist wireframe sogltf) #f)

_new = (clas,...args) => new clas(...args)
_newx = (clas,...args) => (console.log('_newx',clas), new clas(...args))
class foo { constructor(x,y,z) { console.log('FO',x,y,z) } }
_cst1__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKLCc^-CcUcHcWcXcUcQCcOcLcP^-c`L"));

_cst0__limina = new _Box(_cst1__limina);

_cst2__limina = _i("##host-function-memoized");

_cst4__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKLCc^-CcUcHcWcXcUcQCc2cEcMcHcFcWQcNcHc!cV^-c`L"));

_cst3__limina = new _Box(_cst4__limina);

_cst5__limina = _i("%%object-keys");

_cst6__limina = _i("%object->alist");

_cst8__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,ULCc^-CcUcHcWcXcUcQCcIcRcUcHcLcJcQcBcIcQcVc>cBe,Tc@`cBe,U^-c`L"));

_cst7__limina = new _Box(_cst8__limina);

_cst9__limina = new _ScmString(_z("cNcEcDcOcO"));

_cst10__limina = new _ScmString(_z("cNcEcRc["));

_cst11__limina = new _ScmString(_z("cScEcRc["));

_cst13__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKLCc^-CcUcHcWcXcUcQCcVcRcJcOcWcI^-c`L"));

_cst12__limina = new _Box(_cst13__limina);

_cst14__limina = _i("sogltf");

_cst16__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKLCc^-CcUcHcWcXcUcQCcZcLcUcHcIcUcDcPcH^-c`L"));

_cst15__limina = new _Box(_cst16__limina);

_cst17__limina = _i("wireframe");

_cst18__limina = new _ScmString(_z("cOcRcZcDcOcN"));

_cst19__limina = new _ScmString(_z("cOcRcZcDcOcN"));

_cst20__limina = new _ScmString(_z("cTcEcRc["));

_cst22__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,UOcBe,VLCc^-CcUcHcWcXcUcQCcBe,Tc>cBe,Uc@`cBe,V^-c`L"));

_cst21__limina = new _Box(_cst22__limina);

_cst23__limina = _make_interned_keyword("onload");

_cst24__limina = new _ScmString(_z("cGcLcScVcKcLcW"));

_cst25__limina = _i("*limina-revision*");

_cst26__limina = new _ScmString(_z("cOcLcPcLcQcDCcUcHcYcLcVcLcRcQ]CV[X"));

_cst28__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TLCc^-CcUcHcWcXcUcQCcFcRcQcVcRcOcHQcOcRcJQcDcScScOc!KcQcXcOcOOcBe,TL^-c`L"));

_cst27__limina = new _Box(_cst28__limina);

_cst29__limina = new _ScmString(_z("^^Cc>cOcLcPc@"));

_cst30__limina = _i("srfi/1#cons");

_cst32__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TLCc^-CcUcHcWcXcUcQCcGcRcFcXcPcHcQcWQcFcUcHcDcWcHc(cOcHcPcHcQcWKcBe,TL^-c`L"));

_cst31__limina = new _Box(_cst32__limina);

_cst33__limina = new _ScmString(_z("cGcLcY"));

_cst35__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,UOcBe,VLCc^-CcUcHcWcXcUcQCcBe,VQcVcHcWc$cWcWcUcLcEcXcWcHKcBe,TOcBe,UL^-c`L"));

_cst34__limina = new _Box(_cst35__limina);

_cst36__limina = new _ScmString(_z("cLcG"));

_cst37__limina = new _ScmString(_z("cUcHcScOcGcLcY"));

_cst38__limina = new _ScmString(_z("cFcOcDcVcV"));

_cst40__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TLCc^-CcUcHcWcXcUcQCcGcRcFcXcPcHcQcWQcTcXcHcUc!c6cHcOcHcFcWcRcUKcBe,TL^-c`L"));

_cst39__limina = new _Box(_cst40__limina);

_cst41__limina = new _ScmString(_z("cEcRcGc!"));

_cst43__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,ULCc^-CcUcHcWcXcUcQCcBe,UQcDcScScHcQcGc&cKcLcOcGKcBe,TL^-c`L"));

_cst42__limina = new _Box(_cst43__limina);

_cst45__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,ULCc^-CcUcHcWcXcUcQCcBcQcHcZKcHc[cScRcUcWcVQc/c,c0c,c1c$Qc/cLcPOcBe,TOcBe,UL^-c`L"));

_cst44__limina = new _Box(_cst45__limina);

_cst46__limina = new _ScmString(_z("cOS"));

_cst47__limina = new _ScmString(_z("cGcLcY"));

_cst48__limina = new _ScmString(_z("cLcG"));

_cst49__limina = new _ScmString(_z("cScDcQcHcO"));

_cst50__limina = new _ScmString(_z("cFcOcDcVcV"));

_cst51__limina = new _ScmString(_z("cEcRcGc!"));

_cst52__limina = _i("hacky-thread");

_cst53__limina = new _ScmString(_z("cOcLcP"));

_cst54__limina = _i("thread-sleep!");

_cst55__limina = new _ScmString(_z("cKcRcPcH"));

_cst56__limina = _make_interned_keyword("home");

_cst58__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,UOcBe,VOcBe,WLCc^-CcUcHcWcXcUcQCcBe,Vc>cBe,Wc@QcDcScScOc!KcBe,TOcBe,UL^-c`L"));

_cst57__limina = new _Box(_cst58__limina);

_cst59__limina = new _ScmString(_z("cGcLcY"));

_cst60__limina = new _ScmString(_z("cLcG"));

_cst61__limina = new _ScmString(_z("cGcLcY"));

_cst62__limina = new _ScmString(_z("cLcG"));

_cst63__limina = new _ScmString(_z("cScDcQcHcO"));

_cst64__limina = new _ScmString(_z("cFcOcDcVcV"));

_cst65__limina = new _ScmString(_z("cEcRcGc!"));

_cst67__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,ULCc^-CcUcHcWcXcUcQCcBe,Tc>cBe,Uc@^-c`L"));

_cst66__limina = new _Box(_cst67__limina);

_cst69__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,UOcBe,VLCc^-CcUcHcWcXcUcQCcBe,Tc>cBe,Uc@`cBe,V^-c`L"));

_cst68__limina = new _Box(_cst69__limina);

_cst71__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,UOcBe,VOcBe,WLCc^-CcUcHcWcXcUcQCcBe,Vc>cBe,Wc@QcDcScScOc!KcBe,TOcBe,UL^-c`L"));

_cst70__limina = new _Box(_cst71__limina);

_cst73__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,ULCc^-CcUcHcWcXcUcQCcBe,Tc>EcVcWc!cOcHEc@c>cBe,Uc@^-c`L"));

_cst72__limina = new _Box(_cst73__limina);

_cst75__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,UOcBe,VLCc^-CcUcHcWcXcUcQCcBe,Tc>EcVcWc!cOcHEc@c>cBe,Uc@`cBe,V^-c`L"));

_cst74__limina = new _Box(_cst75__limina);

_cst76__limina = new _ScmString(_z("cVcFcUcLcScW"));

_cst77__limina = new _ScmString(_z("cWcHc[cWRcMcDcYcDcVcFcUcLcScW"));

_cst78__limina = new _ScmString(_z("cWc!cScH"));

_cst79__limina = _i("make-mutex");

_cst81__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,ULCc^-CcUcHcWcXcUcQCcBe,TQcRcQcOcRcDcG`cBe,U^-c`L"));

_cst80__limina = new _Box(_cst81__limina);

_cst82__limina = _i("mutex-lock!");

_cst83__limina = new _ScmString(_z("cVcUcF"));

_cst85__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKLCc^-CcUcHcWcXcUcQCcGcRcFcXcPcHcQcWQcKcHcDcG^-c`L"));

_cst84__limina = new _Box(_cst85__limina);

_cst86__limina = _i("mutex-unlock!");

_cst88__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TLCc^-CcUcHcWcXcUcQCc2cEcMcHcFcWQcNcHc!cVKcBe,TL^-c`L"));

_cst87__limina = new _Box(_cst88__limina);

_cst89__limina = _i("vector->list");

_cst91__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TLCc^-CcUcHcWcXcUcQCc2cEcMcHcFcWQcYcDcOcXcHcVKcBe,TL^-c`L"));

_cst90__limina = new _Box(_cst91__limina);

_cst93__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TLCc^-CcUcHcWcXcUcQCc2cEcMcHcFcWQcHcQcWcUcLcHcVKcBe,TL^-c`L"));

_cst92__limina = new _Box(_cst93__limina);

_cst94__limina = _i("srfi/1#map");

_cst96__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,ULCc^-CcUcHcWcXcUcQCcWc!cScHcRcICcBe,T```EcRcEcMcHcFcWEIIcBe,UD`cQcXcOcO^-c`L"));

_cst95__limina = new _Box(_cst96__limina);

_cst97__limina = _i("srfi/1#car");

_cst98__limina = _i("srfi/1#cadr");

_cst99__limina = _i("srfi/1#null?");

_cst100__limina = _i("srfi/1#list");

_cst101__limina = _i("srfi/69#alist->hash-table");

_cst102__limina = _i("string-append");

_cst104__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,UOcBe,VLCc^-CcUcHcWcXcUcQCcZcLcQcGcRcZc>cBe,Tc@`cBe,Uc>cBe,Vc@^-c`L"));

_cst103__limina = new _Box(_cst104__limina);

_cst105__limina = _i("entries");

_cst107__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,UOcBe,VLCc^-CcUcHcWcXcUcQCcBcQcHcZKc7c+c5c(c(Qc%cRc[c%cXcIcIcHcUc*cHcRcPcHcWcUc!OcBe,TOcBe,UOcBe,VL^-c`L"));

_cst106__limina = new _Box(_cst107__limina);

_cst109__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKLCc^-CcUcHcWcXcUcQCcBcQcHcZKc7c+c5c(c(Qc0cHcVcKc3cKc!cVcLcFcDcOc0cDcWcHcUcLcDcOL^-c`L"));

_cst108__limina = new _Box(_cst109__limina);

_cst111__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,ULCc^-CcUcHcWcXcUcQCcBcQcHcZKc7c+c5c(c(Qc0cHcVcKOcBe,TOcBe,UL^-c`L"));

_cst110__limina = new _Box(_cst111__limina);

_cst112__limina = _make_interned_keyword("color");

_cst113__limina = _make_interned_keyword("setHex");

_cst114__limina = _make_interned_keyword("opacity");

_cst115__limina = _make_interned_keyword("transparent");

_cst116__limina = _make_interned_keyword("position");

_cst117__limina = _make_interned_keyword("set");

_cst118__limina = _make_interned_keyword("rotation");

_cst120__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,UOcBe,VLCc^-CcUcHcWcXcUcQCcBcQcHcZKc7c+c5c(c(Qc9cHcFcWcRcUVOcBe,TOcBe,UOcBe,VL^-c`L"));

_cst119__limina = new _Box(_cst120__limina);

_cst122__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,UOcBe,VLCc^-CcUcHcWcXcUcQCcBcQcHcZKc7c+c5c(c(Qc6cScKcHcUcHc%cXcIcIcHcUc*cHcRcPcHcWcUc!OcBe,TOcBe,UOcBe,VL^-c`L"));

_cst121__limina = new _Box(_cst122__limina);

_cst124__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TLCc^-CcUcHcWcXcUcQCcBcQcHcZKc7c+c5c(c(Qc0cHcVcKc3cKc!cVcLcFcDcOc0cDcWcHcUcLcDcOOcBe,TL^-c`L"));

_cst123__limina = new _Box(_cst124__limina);

_cst126__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,ULCc^-CcUcHcWcXcUcQCcBcQcHcZKc7c+c5c(c(Qc0cHcVcKOcBe,TOcBe,UL^-c`L"));

_cst125__limina = new _Box(_cst126__limina);

_cst127__limina = _make_interned_keyword("wireframe");

_cst128__limina = _make_interned_keyword("receiveShadow");

_cst129__limina = _make_interned_keyword("castShadow");

_cst130__limina = new _ScmString(_z("cNcEcDcOcO"));

_cst131__limina = _make_interned_keyword("tag");

_cst132__limina = new _ScmString(_z("cNcEcRc["));

_cst134__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,UOcBe,VLCc^-CcUcHcWcXcUcQCcBcQcHcZKc7c+c5c(c(Qc%cRc[c*cHcRcPcHcWcUc!OcBe,TOcBe,UOcBe,VL^-c`L"));

_cst133__limina = new _Box(_cst134__limina);

_cst136__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TLCc^-CcUcHcWcXcUcQCcBcQcHcZKc7c+c5c(c(Qc0cHcVcKc3cKc!cVcLcFcDcOc0cDcWcHcUcLcDcOOcBe,TL^-c`L"));

_cst135__limina = new _Box(_cst136__limina);

_cst138__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,ULCc^-CcUcHcWcXcUcQCcBcQcHcZKc7c+c5c(c(Qc0cHcVcKOcBe,TOcBe,UL^-c`L"));

_cst137__limina = new _Box(_cst138__limina);

_cst139__limina = new _ScmString(_z("cScEcRc["));

_cst141__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,UOcBe,VLCc^-CcUcHcWcXcUcQCcBcQcHcZKc7c+c5c(c(Qc%cRc[c*cHcRcPcHcWcUc!OcBe,TOcBe,UOcBe,VL^-c`L"));

_cst140__limina = new _Box(_cst141__limina);

_cst143__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TLCc^-CcUcHcWcXcUcQCcBcQcHcZKc7c+c5c(c(Qc0cHcVcKc3cKcRcQcJc0cDcWcHcUcLcDcOOcBe,TL^-c`L"));

_cst142__limina = new _Box(_cst143__limina);

_cst145__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,ULCc^-CcUcHcWcXcUcQCcBcQcHcZKc7c+c5c(c(Qc0cHcVcKOcBe,TOcBe,UL^-c`L"));

_cst144__limina = new _Box(_cst145__limina);

_cst146__limina = new _ScmString(_z("cTcEcRc["));

_cst147__limina = _i("later");

_cst148__limina = _make_interned_keyword("seturl");

_cst149__limina = new _ScmString(_z("cWcPcSRcIcRcRQcKcWcPcO"));

_cst150__limina = new _ScmString(_z("cFcDcQcYcDcV"));

_cst151__limina = new _ScmString(_z("UcG"));

_cst152__limina = _make_interned_keyword("getContext");

_cst154__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TLCc^-CcUcHcWcXcUcQCcBcQcHcZKc7c+c5c(c(Qc&cDcQcYcDcVc7cHc[cWcXcUcHOcBe,TL^-c`L"));

_cst153__limina = new _Box(_cst154__limina);

_cst156__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,UOcBe,VLCc^-CcUcHcWcXcUcQCcBcQcHcZKc7c+c5c(c(Qc%cRc[c%cXcIcIcHcUc*cHcRcPcHcWcUc!OcBe,TOcBe,UOcBe,VL^-c`L"));

_cst155__limina = new _Box(_cst156__limina);

_cst158__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TLCc^-CcUcHcWcXcUcQCcBcQcHcZKc7c+c5c(c(Qc0cHcVcKc%cDcVcLcFc0cDcWcHcUcLcDcOOcBe,TL^-c`L"));

_cst157__limina = new _Box(_cst158__limina);

_cst160__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,ULCc^-CcUcHcWcXcUcQCcBcQcHcZKc7c+c5c(c(Qc0cHcVcKOcBe,TOcBe,UL^-c`L"));

_cst159__limina = new _Box(_cst160__limina);

_cst161__limina = _make_interned_keyword("map");

_cst162__limina = _make_interned_keyword("clearRect");

_cst163__limina = _make_interned_keyword("drawImage");

_cst164__limina = _make_interned_keyword("needsUpdate");

_cst165__limina = _make_interned_keyword("image");

_cst166__limina = _make_interned_keyword("width");

_cst167__limina = _make_interned_keyword("height");

_cst168__limina = _make_interned_keyword("canvas");

_cst170__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,UOcBe,VOcBe,WLCc^-CcUcHcWcXcUcQCcUcDcVcWcHcUcLc]cHc+c7c0c/QcGcUcDcZc+c7c0c/KcBe,VOcBe,WLQcWcKcHcQKcBe,ULQcWcKcHcQKcBe,TL^-c`L"));

_cst169__limina = new _Box(_cst170__limina);

_cst171__limina = _make_interned_keyword("sethtml");

_cst173__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,UOcBe,VLCc^-CcUcHcWcXcUcQCcUcDcVcWcHcUcLc]cHc+c7c0c/QcGcUcDcZc8c5c/KcBe,UOcBe,VLQcWcKcHcQKcBe,TL^-c`L"));

_cst172__limina = new _Box(_cst173__limina);

_cst174__limina = new _ScmString(_z("cKcWcPcOcEcRc["));

_cst176__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKLCc^-CcUcHcWcXcUcQCcBcQcHcZKc7c+c5c(c(Qc%cXcIcIcHcUc*cHcRcPcHcWcUc!L^-c`L"));

_cst175__limina = new _Box(_cst176__limina);

_cst177__limina = _i("[...]");

_cst179__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,ULCc^-CcUcHcWcXcUcQCcBcQcHcZKc7c+c5c(c(Qc)cOcRcDcWVUc%cXcIcIcHcUc$cWcWcUcLcEcXcWcHOcBe,TOcBe,UL^-c`L"));

_cst178__limina = new _Box(_cst179__limina);

_cst180__limina = _i("setAttribute");

_cst182__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,ULCc^-CcUcHcWcXcUcQCcBcQcHcZKc7c+c5c(c(Qc)cOcRcDcWVUc%cXcIcIcHcUc$cWcWcUcLcEcXcWcHOcBe,TOcBe,UL^-c`L"));

_cst181__limina = new _Box(_cst182__limina);

_cst184__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKLCc^-CcUcHcWcXcUcQCcBcQcHcZKc7c+c5c(c(Qc7cHc[cWcXcUcHc/cRcDcGcHcUL^-c`L"));

_cst183__limina = new _Box(_cst184__limina);

_cst185__limina = new _ScmString(_z("cWcPcSRcGcLcVcFQcScQcJ"));

_cst186__limina = _make_interned_keyword("load");

_cst188__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TLCc^-CcUcHcWcXcUcQCcBcQcHcZKc7c+c5c(c(Qc3cRcLcQcWcVc0cDcWcHcUcLcDcOOcBe,TL^-c`L"));

_cst187__limina = new _Box(_cst188__limina);

_cst190__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TOcBe,ULCc^-CcUcHcWcXcUcQCcBcQcHcZKc7c+c5c(c(Qc3cRcLcQcWcVOcBe,TOcBe,UL^-c`L"));

_cst189__limina = new _Box(_cst190__limina);

_cst191__limina = new _ScmString(_z("cScRcLcQcWcV"));

_cst193__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TLCc^-CcUcHcWcXcUcQCcBcQcHcZKc5cDc!cPcDcUcFcKcHcUOcBe,TL^-c`L"));

_cst192__limina = new _Box(_cst193__limina);

_cst194__limina = _i("gen-layers");

_cst195__limina = _make_interned_keyword("layers");

_cst196__limina = _make_interned_keyword("scene");

_cst197__limina = _make_interned_keyword("add");

_cst198__limina = _make_interned_keyword("composer0");

_cst199__limina = _make_interned_keyword("composer");

_cst201__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TLCc^-CcUcHcWcXcUcQCcOcLcPQcFcHcOcOQcRcEcMKcBe,TL^-c`L"));

_cst200__limina = new _Box(_cst201__limina);

_cst203__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TLCc^-CcUcHcWcXcUcQCcOcLcPQcFcHcOcOQcRcEcMcVKcBe,TL^-c`L"));

_cst202__limina = new _Box(_cst203__limina);

_cst205__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TLCc^-CcUcHcWcXcUcQCcVcHcWc7cLcPcHcRcXcWKcBe,TOSL^-c`L"));

_cst204__limina = new _Box(_cst205__limina);

_cst207__limina = new _ScmString(_z("KcDcVc!cQcFCcIcXcQcFcWcLcRcQCKcBe,TLCc^-CcUcHcWcXcUcQCcVcHcWc7cLcPcHcRcXcWKcBe,TOSL^-c`L"));

_cst206__limina = new _Box(_cst207__limina);

_m(_bb1_limina_23_ = () => {
if (_n !== 0) {
return _w(_bb1_limina_23_);
}
_s[_t+1] = _r;
_a = _cst0__limina;
++_t;
return _p(_bb2_limina_23_);
},-1,_i("limina#"),!1,!0);

_j(_bb2_limina_23_ = () => {
_r = _bb3_limina_23_;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_limina_23_ = () => {
_r = _bb4_limina_23_;
_n = 0;
return _check_procedure(_a);
},1,1);

_k(_bb4_limina_23_ = () => {
_g["lim"] = _a;
_a = _cst3__limina;
_r = _bb5_limina_23_;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},1,1);

_k(_bb5_limina_23_ = () => {
_r = _bb6_limina_23_;
_n = 0;
return _check_procedure(_a);
},1,1);

_k(_bb6_limina_23_ = () => {
_g["%%object-keys"] = _a;
_g["%object->alist"] = _bb1__25_deep_2d_object_2d__3e_alist;
_a = _cst7__limina;
_r = _bb7_limina_23_;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},1,1);

_k(_bb7_limina_23_ = () => {
_b = _bb1_kball;
_s[_t+1] = _a;
_a = _cst9__limina;
_r = _bb8_limina_23_;
_n = 2;
return _check_procedure(_s[_t+1])();
},1,1);

_k(_bb8_limina_23_ = () => {
_a = _cst7__limina;
_r = _bb9_limina_23_;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},1,1);

_k(_bb9_limina_23_ = () => {
_b = _bb1_kbox;
_s[_t+1] = _a;
_a = _cst10__limina;
_r = _bb10_limina_23_;
_n = 2;
return _check_procedure(_s[_t+1])();
},1,1);

_k(_bb10_limina_23_ = () => {
_a = _cst7__limina;
_r = _bb11_limina_23_;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},1,1);

_k(_bb11_limina_23_ = () => {
_b = _bb1_pbox;
_s[_t+1] = _a;
_a = _cst11__limina;
_r = _bb12_limina_23_;
_n = 2;
return _check_procedure(_s[_t+1])();
},1,1);

_k(_bb12_limina_23_ = () => {
_a = _cst12__limina;
_r = _bb13_limina_23_;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},1,1);

_k(_bb13_limina_23_ = () => {
_r = _bb14_limina_23_;
_n = 0;
return _check_procedure(_a);
},1,1);

_k(_bb14_limina_23_ = () => {
_g["sogltf"] = _a;
_a = _cst15__limina;
_r = _bb15_limina_23_;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},1,1);

_k(_bb15_limina_23_ = () => {
_r = _bb16_limina_23_;
_n = 0;
return _check_procedure(_a);
},1,1);

_k(_bb16_limina_23_ = () => {
_g["wireframe"] = _a;
_a = _cst7__limina;
_r = _bb17_limina_23_;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},1,1);

_k(_bb17_limina_23_ = () => {
_b = _bb23_limina_23_;
_s[_t+1] = _a;
_a = _cst18__limina;
_r = _bb18_limina_23_;
_n = 2;
return _check_procedure(_s[_t+1])();
},1,1);

_l(_bb23_limina_23_ = () => {
if (_n !== 0) {
return _w(_bb23_limina_23_);
}
_s[_t+1] = _r;
_a = _cst19__limina;
++_t;
return _p(_bb24_limina_23_);
},-1);

_k(_bb18_limina_23_ = () => {
_a = _cst7__limina;
_r = _bb19_limina_23_;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},1,1);

_j(_bb24_limina_23_ = () => {
_r = _bb25_limina_23_;
_n = 1;
return _u(_g["sogltf"],_cst14__limina)();
});

_k(_bb19_limina_23_ = () => {
_b = _bb1_qbox;
_s[_t+1] = _a;
_a = _cst20__limina;
_r = _bb20_limina_23_;
_n = 2;
return _check_procedure(_s[_t+1])();
},1,1);

_k(_bb25_limina_23_ = () => {
var closure0 = _closure_alloc([_bb28_limina_23_,_a]);
_s[_t+1] = closure0;
_s[_t+2] = _a;
_a = _cst21__limina;
_r = _bb26_limina_23_;
_n = 1;
_t += 2;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},1,1);

_k(_bb20_limina_23_ = () => {
_a = _cst7__limina;
_r = _bb21_limina_23_;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},1,1);

_l(_bb28_limina_23_ = () => {
if (_n !== 0) {
return _w(_d);
}
_a = _d(!0)[1];
_b = !1;
return _p(_bb29_limina_23_);
},1);

_k(_bb26_limina_23_ = () => {
_c = _s[_t-1];
_s[_t-1] = _a;
_a = _s[_t];
_b = _cst23__limina;
_r = _bb27_limina_23_;
_n = 3;
return _check_procedure(_s[_t-1])();
},3,1);

_k(_bb21_limina_23_ = () => {
_b = _bb1_dipshit;
_s[_t+1] = _a;
_a = _cst24__limina;
_r = _bb22_limina_23_;
_n = 2;
return _check_procedure(_s[_t+1])();
},1,1);

_j(_bb29_limina_23_ = () => {
_n = 2;
return _u(_g["wireframe"],_cst17__limina)();
});

_k(_bb27_limina_23_ = () => {
_a = _s[_t];
_t -= 3;
return _s[_t+1]();
},3,1);

_k(_bb22_limina_23_ = () => {
_g["*limina-revision*"] = _cst26__limina;
_a = void 0;
--_t;
return _s[_t+1]();
},1,1);



_m(_bb1_nerk = () => {
if (_n === 0) {
_a = null;
} else {
if (!_build_rest(0)) {
return _w(_bb1_nerk);
}
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_a = _cst27__limina;
_t += 2;
return _p(_bb2_nerk);
},-1,_i("nerk"),!1,!0);

_j(_bb2_nerk = () => {
_r = _bb3_nerk;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_nerk = () => {
_s[_t+1] = _a;
_b = _s[_t];
_a = _cst29__limina;
_r = _bb4_nerk;
_n = 2;
++_t;
return _u(_g["srfi/1#cons"],_cst30__limina)();
},2,1);

_k(_bb4_nerk = () => {
_r = _s[_t-2];
return _p(_bb5_nerk);
},3,1);

_j(_bb5_nerk = () => {
_n = 1;
_t -= 3;
return _check_procedure(_s[_t+3])();
});



_m(_bb1_new_2d_repl = () => {
if (_n !== 1) {
return _w(_bb1_new_2d_repl);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_a = _cst31__limina;
_t += 2;
return _p(_bb2_new_2d_repl);
},-1,_i("new-repl"),!1,!0);

_j(_bb2_new_2d_repl = () => {
_r = _bb3_new_2d_repl;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_new_2d_repl = () => {
_s[_t+1] = _a;
_a = _cst33__limina;
_r = _bb4_new_2d_repl;
_n = 1;
return _check_procedure(_s[_t+1])();
},2,1);

_k(_bb4_new_2d_repl = () => {
_s[_t+1] = _a;
_a = _cst34__limina;
_r = _bb5_new_2d_repl;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},2,1);

_k(_bb5_new_2d_repl = () => {
_c = _s[_t];
_b = _s[_t-1];
_s[_t-1] = _a;
_a = _cst36__limina;
_r = _bb6_new_2d_repl;
_n = 3;
return _check_procedure(_s[_t-1])();
},3,1);

_k(_bb6_new_2d_repl = () => {
_a = _cst34__limina;
_r = _bb7_new_2d_repl;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},3,1);

_k(_bb7_new_2d_repl = () => {
_c = _s[_t];
_b = _cst37__limina;
_s[_t-1] = _a;
_a = _cst38__limina;
_r = _bb8_new_2d_repl;
_n = 3;
return _check_procedure(_s[_t-1])();
},3,1);

_k(_bb8_new_2d_repl = () => {
_a = _cst39__limina;
_r = _bb9_new_2d_repl;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},3,1);

_k(_bb9_new_2d_repl = () => {
_s[_t-1] = _a;
_a = _cst41__limina;
_r = _bb10_new_2d_repl;
_n = 1;
return _check_procedure(_s[_t-1])();
},3,1);

_k(_bb10_new_2d_repl = () => {
_s[_t-1] = _a;
_a = _cst42__limina;
_r = _bb11_new_2d_repl;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},3,1);

_k(_bb11_new_2d_repl = () => {
_b = _s[_t-1];
_s[_t-1] = _a;
_a = _s[_t];
_r = _bb12_new_2d_repl;
_n = 2;
return _check_procedure(_s[_t-1])();
},3,1);

_k(_bb12_new_2d_repl = () => {
_a = _s[_t];
_t -= 3;
return _s[_t+1]();
},3,1);



_m(_bb1_native_2d_limina_2d_constructor = () => {
if (_n !== 2) {
return _w(_bb1_native_2d_limina_2d_constructor);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_s[_t+3] = _b;
_a = _cst44__limina;
_t += 3;
return _p(_bb2_native_2d_limina_2d_constructor);
},-1,_i("native-limina-constructor"),!1,!0);

_j(_bb2_native_2d_limina_2d_constructor = () => {
_r = _bb3_native_2d_limina_2d_constructor;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_native_2d_limina_2d_constructor = () => {
_b = _s[_t];
_s[_t] = _a;
_a = _s[_t-1];
_r = _s[_t-2];
return _p(_bb4_native_2d_limina_2d_constructor);
},3,1);

_j(_bb4_native_2d_limina_2d_constructor = () => {
_n = 2;
_t -= 3;
return _check_procedure(_s[_t+3])();
});



_m(_bb1_new_2d_limina = () => {
if (_n === 1) {
_b = _cst46__limina;
} else {
if (_n !== 2) {
return _w(_bb1_new_2d_limina);
}
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_s[_t+3] = _b;
_a = _cst31__limina;
_t += 3;
return _p(_bb2_new_2d_limina);
},-1,_i("new-limina"),!1,!0);

_j(_bb2_new_2d_limina = () => {
_r = _bb3_new_2d_limina;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_new_2d_limina = () => {
_s[_t+1] = _a;
_a = _cst47__limina;
_r = _bb4_new_2d_limina;
_n = 1;
return _check_procedure(_s[_t+1])();
},3,1);

_k(_bb4_new_2d_limina = () => {
_s[_t+1] = _a;
_a = _cst34__limina;
_r = _bb5_new_2d_limina;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},3,1);

_k(_bb5_new_2d_limina = () => {
_c = _s[_t];
_b = _s[_t-2];
_s[_t-2] = _a;
_a = _cst48__limina;
_r = _bb6_new_2d_limina;
_n = 3;
return _check_procedure(_s[_t-2])();
},4,1);

_k(_bb6_new_2d_limina = () => {
_a = _cst34__limina;
_r = _bb7_new_2d_limina;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},4,1);

_k(_bb7_new_2d_limina = () => {
_c = _s[_t];
_b = _cst49__limina;
_s[_t-2] = _a;
_a = _cst50__limina;
_r = _bb8_new_2d_limina;
_n = 3;
return _check_procedure(_s[_t-2])();
},4,1);

_k(_bb8_new_2d_limina = () => {
_a = _cst39__limina;
_r = _bb9_new_2d_limina;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},4,1);

_k(_bb9_new_2d_limina = () => {
_s[_t-2] = _a;
_a = _cst51__limina;
_r = _bb10_new_2d_limina;
_n = 1;
return _check_procedure(_s[_t-2])();
},4,1);

_k(_bb10_new_2d_limina = () => {
_s[_t-2] = _a;
_a = _cst42__limina;
_r = _bb11_new_2d_limina;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},4,1);

_k(_bb11_new_2d_limina = () => {
_b = _s[_t-2];
_s[_t-2] = _a;
_a = _s[_t];
_r = _bb12_new_2d_limina;
_n = 2;
return _check_procedure(_s[_t-2])();
},4,1);

_k(_bb12_new_2d_limina = () => {
_a = _cst44__limina;
_r = _bb13_new_2d_limina;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},4,1);

_k(_bb13_new_2d_limina = () => {
_b = _s[_t-1];
_s[_t-2] = _a;
_a = _s[_t];
_r = _bb14_new_2d_limina;
_n = 2;
_t -= 3;
return _check_procedure(_s[_t+1])();
},4,1);

_k(_bb14_new_2d_limina = () => {
_s[_t+1] = _a;
var closure0 = _closure_alloc([_bb29_new_2d_limina,_a]);
_s[_t+2] = closure0;
_a = _s[_t+2];
_r = _bb15_new_2d_limina;
_n = 1;
++_t;
return _u(_g["hacky-thread"],_cst52__limina)();
},1,1);

_l(_bb29_new_2d_limina = () => {
if (_n !== 0) {
return _w(_d);
}
_s[_t+1] = _r;
_s[_t+2] = _d;
_a = 1;
_t += 2;
return _p(_bb30_new_2d_limina);
},1);

_k(_bb15_new_2d_limina = () => {
_b = _s[_t];
_a = _cst53__limina;
_r = _bb28_new_2d_limina;
_n = 2;
return _bb17_new_2d_limina();
},2,1);

_j(_bb30_new_2d_limina = () => {
_r = _bb16_new_2d_limina;
_n = 1;
return _u(_g["thread-sleep!"],_cst54__limina)();
});

_l(_bb17_new_2d_limina = () => {
if (_n === 0) {
_a = null;
} else {
if (!_build_rest(0)) {
return _w(_bb17_new_2d_limina);
}
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_a = _cst27__limina;
_t += 2;
return _p(_bb18_new_2d_limina);
},-1);

_k(_bb28_new_2d_limina = () => {
_a = _s[_t];
_t -= 2;
return _s[_t+1]();
},2,1);

_k(_bb16_new_2d_limina = () => {
_a = _cst55__limina;
_r = _bb22_new_2d_limina;
_n = 1;
return _bb17_new_2d_limina();
},2,1);

_j(_bb18_new_2d_limina = () => {
_r = _bb19_new_2d_limina;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb22_new_2d_limina = () => {
_a = _s[_t](!0)[1];
_b = _cst56__limina;
_r = _s[_t-1];
return _p(_bb23_new_2d_limina);
},2,1);

_k(_bb19_new_2d_limina = () => {
_s[_t+1] = _a;
_b = _s[_t];
_a = _cst29__limina;
_r = _bb20_new_2d_limina;
_n = 2;
++_t;
return _u(_g["srfi/1#cons"],_cst30__limina)();
},2,1);

_j(_bb23_new_2d_limina = () => {
_n = 2;
_t -= 2;
return _bb24_new_2d_limina();
});

_k(_bb20_new_2d_limina = () => {
_r = _s[_t-2];
return _p(_bb21_new_2d_limina);
},3,1);

_l(_bb24_new_2d_limina = () => {
if (_n === 2) {
_c = null;
} else {
if (!_build_rest(2)) {
return _w(_bb24_new_2d_limina);
}
}
_s[_t+1] = _a;
_s[_t+2] = _r;
_s[_t+3] = _a;
_s[_t+4] = _b;
_s[_t+5] = _c;
_a = _cst57__limina;
_t += 5;
return _p(_bb25_new_2d_limina);
},-1);

_j(_bb21_new_2d_limina = () => {
_n = 1;
_t -= 3;
return _check_procedure(_s[_t+3])();
});

_j(_bb25_new_2d_limina = () => {
_r = _bb26_new_2d_limina;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb26_new_2d_limina = () => {
_c = _s[_t-1];
_b = _s[_t-2];
_s[_t-2] = _a;
_a = _s[_t];
_r = _s[_t-3];
return _p(_bb27_new_2d_limina);
},5,2);

_j(_bb27_new_2d_limina = () => {
_n = 4;
_t -= 4;
return _check_procedure(_s[_t+2])();
});



_m(_bb1_div = () => {
if (_n !== 1) {
return _w(_bb1_div);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_a = _cst31__limina;
_t += 2;
return _p(_bb2_div);
},-1,_i("div"),!1,!0);

_j(_bb2_div = () => {
_r = _bb3_div;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_div = () => {
_s[_t+1] = _a;
_a = _cst59__limina;
_r = _bb4_div;
_n = 1;
return _check_procedure(_s[_t+1])();
},2,1);

_k(_bb4_div = () => {
_s[_t+1] = _a;
_a = _cst34__limina;
_r = _bb5_div;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},2,1);

_k(_bb5_div = () => {
_c = _s[_t];
_b = _s[_t-1];
_s[_t-1] = _a;
_a = _cst60__limina;
_r = _bb6_div;
_n = 3;
return _check_procedure(_s[_t-1])();
},3,1);

_k(_bb6_div = () => {
_a = _s[_t];
_t -= 3;
return _s[_t+1]();
},3,1);



_m(_bb1_limina_2d_div = () => {
if (_n !== 1) {
return _w(_bb1_limina_2d_div);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_a = _cst31__limina;
_t += 2;
return _p(_bb2_limina_2d_div);
},-1,_i("limina-div"),!1,!0);

_j(_bb2_limina_2d_div = () => {
_r = _bb3_limina_2d_div;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_limina_2d_div = () => {
_s[_t+1] = _a;
_a = _cst61__limina;
_r = _bb4_limina_2d_div;
_n = 1;
return _check_procedure(_s[_t+1])();
},2,1);

_k(_bb4_limina_2d_div = () => {
_s[_t+1] = _a;
_a = _cst34__limina;
_r = _bb5_limina_2d_div;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},2,1);

_k(_bb5_limina_2d_div = () => {
_c = _s[_t];
_b = _s[_t-1];
_s[_t-1] = _a;
_a = _cst62__limina;
_r = _bb6_limina_2d_div;
_n = 3;
return _check_procedure(_s[_t-1])();
},3,1);

_k(_bb6_limina_2d_div = () => {
_a = _cst34__limina;
_r = _bb7_limina_2d_div;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},3,1);

_k(_bb7_limina_2d_div = () => {
_c = _s[_t];
_b = _cst63__limina;
_s[_t-1] = _a;
_a = _cst64__limina;
_r = _bb8_limina_2d_div;
_n = 3;
return _check_procedure(_s[_t-1])();
},3,1);

_k(_bb8_limina_2d_div = () => {
_a = _cst39__limina;
_r = _bb9_limina_2d_div;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},3,1);

_k(_bb9_limina_2d_div = () => {
_s[_t-1] = _a;
_a = _cst65__limina;
_r = _bb10_limina_2d_div;
_n = 1;
return _check_procedure(_s[_t-1])();
},3,1);

_k(_bb10_limina_2d_div = () => {
_s[_t-1] = _a;
_a = _cst42__limina;
_r = _bb11_limina_2d_div;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},3,1);

_k(_bb11_limina_2d_div = () => {
_b = _s[_t-1];
_s[_t-1] = _a;
_a = _s[_t];
_r = _bb12_limina_2d_div;
_n = 2;
return _check_procedure(_s[_t-1])();
},3,1);

_k(_bb12_limina_2d_div = () => {
_a = _s[_t];
_t -= 3;
return _s[_t+1]();
},3,1);



_m(_bb1_slot = () => {
if (_n !== 2) {
return _w(_bb1_slot);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_s[_t+3] = _b;
_a = _cst66__limina;
_t += 3;
return _p(_bb2_slot);
},-1,_i("slot"),!1,!0);

_j(_bb2_slot = () => {
_r = _bb3_slot;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_slot = () => {
_b = _s[_t];
_s[_t] = _a;
_a = _s[_t-1];
_r = _s[_t-2];
return _p(_bb4_slot);
},3,1);

_j(_bb4_slot = () => {
_n = 2;
_t -= 3;
return _check_procedure(_s[_t+3])();
});



_m(_bb1_slot_21_ = () => {
if (_n !== 3) {
return _w(_bb1_slot_21_);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_s[_t+3] = _b;
_s[_t+4] = _c;
_a = _cst21__limina;
_t += 4;
return _p(_bb2_slot_21_);
},-1,_i("slot!"),!1,!0);

_j(_bb2_slot_21_ = () => {
_r = _bb3_slot_21_;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_slot_21_ = () => {
_c = _s[_t];
_b = _s[_t-1];
_s[_t-1] = _a;
_a = _s[_t-2];
_r = _s[_t-3];
return _p(_bb4_slot_21_);
},4,1);

_j(_bb4_slot_21_ = () => {
_n = 3;
_t -= 4;
return _check_procedure(_s[_t+3])();
});



_m(_bb1_set_2d_slot_21_ = () => {
if (_n !== 3) {
return _w(_bb1_set_2d_slot_21_);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_s[_t+3] = _b;
_s[_t+4] = _c;
_a = _cst68__limina;
_t += 4;
return _p(_bb2_set_2d_slot_21_);
},-1,_i("set-slot!"),!1,!0);

_j(_bb2_set_2d_slot_21_ = () => {
_r = _bb3_set_2d_slot_21_;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_set_2d_slot_21_ = () => {
_c = _s[_t];
_b = _s[_t-1];
_s[_t-1] = _a;
_a = _s[_t-2];
_r = _s[_t-3];
return _p(_bb4_set_2d_slot_21_);
},4,1);

_j(_bb4_set_2d_slot_21_ = () => {
_n = 3;
_t -= 4;
return _check_procedure(_s[_t+3])();
});



_m(_bb1_call = () => {
if (_n === 2) {
_c = null;
} else {
if (!_build_rest(2)) {
return _w(_bb1_call);
}
}
_s[_t+1] = _a;
_s[_t+2] = _r;
_s[_t+3] = _a;
_s[_t+4] = _b;
_s[_t+5] = _c;
_a = _cst57__limina;
_t += 5;
return _p(_bb2_call);
},-1,_i("call"),!1,!0);

_j(_bb2_call = () => {
_r = _bb3_call;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_call = () => {
_c = _s[_t-1];
_b = _s[_t-2];
_s[_t-2] = _a;
_a = _s[_t];
_r = _s[_t-3];
return _p(_bb4_call);
},5,2);

_j(_bb4_call = () => {
_n = 4;
_t -= 4;
return _check_procedure(_s[_t+2])();
});



_m(_bb1_send = () => {
if (_n === 2) {
_c = null;
} else {
if (!_build_rest(2)) {
return _w(_bb1_send);
}
}
_s[_t+1] = _a;
_s[_t+2] = _r;
_s[_t+3] = _a;
_s[_t+4] = _b;
_s[_t+5] = _c;
_a = _cst70__limina;
_t += 5;
return _p(_bb2_send);
},-1,_i("send"),!1,!0);

_j(_bb2_send = () => {
_r = _bb3_send;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_send = () => {
_c = _s[_t-1];
_b = _s[_t-2];
_s[_t-2] = _a;
_a = _s[_t];
_r = _s[_t-3];
return _p(_bb4_send);
},5,2);

_j(_bb4_send = () => {
_n = 4;
_t -= 4;
return _check_procedure(_s[_t+2])();
});



_m(_bb1_get_2d_style = () => {
if (_n !== 2) {
return _w(_bb1_get_2d_style);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_s[_t+3] = _b;
_a = _cst72__limina;
_t += 3;
return _p(_bb2_get_2d_style);
},-1,_i("get-style"),!1,!0);

_j(_bb2_get_2d_style = () => {
_r = _bb3_get_2d_style;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_get_2d_style = () => {
_b = _s[_t];
_s[_t] = _a;
_a = _s[_t-1];
_r = _s[_t-2];
return _p(_bb4_get_2d_style);
},3,1);

_j(_bb4_get_2d_style = () => {
_n = 2;
_t -= 3;
return _check_procedure(_s[_t+3])();
});



_m(_bb1_set_2d_style_21_ = () => {
if (_n !== 3) {
return _w(_bb1_set_2d_style_21_);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_s[_t+3] = _b;
_s[_t+4] = _c;
_a = _cst74__limina;
_t += 4;
return _p(_bb2_set_2d_style_21_);
},-1,_i("set-style!"),!1,!0);

_j(_bb2_set_2d_style_21_ = () => {
_r = _bb3_set_2d_style_21_;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_set_2d_style_21_ = () => {
_c = _s[_t];
_b = _s[_t-1];
_s[_t-1] = _a;
_a = _s[_t-2];
_r = _s[_t-3];
return _p(_bb4_set_2d_style_21_);
},4,1);

_j(_bb4_set_2d_style_21_ = () => {
_n = 3;
_t -= 4;
return _check_procedure(_s[_t+3])();
});



_m(_bb1_select = () => {
if (_n !== 1) {
return _w(_bb1_select);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_a = _cst39__limina;
_t += 2;
return _p(_bb2_select);
},-1,_i("select"),!1,!0);

_j(_bb2_select = () => {
_r = _bb3_select;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_select = () => {
_s[_t+1] = _a;
_a = _s[_t];
_r = _s[_t-1];
++_t;
return _p(_bb4_select);
},2,1);

_j(_bb4_select = () => {
_n = 1;
_t -= 3;
return _check_procedure(_s[_t+3])();
});



_m(_bb1_create_2d_element = () => {
if (_n !== 1) {
return _w(_bb1_create_2d_element);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_a = _cst31__limina;
_t += 2;
return _p(_bb2_create_2d_element);
},-1,_i("create-element"),!1,!0);

_j(_bb2_create_2d_element = () => {
_r = _bb3_create_2d_element;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_create_2d_element = () => {
_s[_t+1] = _a;
_a = _s[_t];
_r = _s[_t-1];
++_t;
return _p(_bb4_create_2d_element);
},2,1);

_j(_bb4_create_2d_element = () => {
_n = 1;
_t -= 3;
return _check_procedure(_s[_t+3])();
});



_m(_bb1_set_2d_attr = () => {
if (_n !== 3) {
return _w(_bb1_set_2d_attr);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_s[_t+3] = _b;
_s[_t+4] = _c;
_a = _cst34__limina;
_t += 4;
return _p(_bb2_set_2d_attr);
},-1,_i("set-attr"),!1,!0);

_j(_bb2_set_2d_attr = () => {
_r = _bb3_set_2d_attr;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_set_2d_attr = () => {
_c = _s[_t-2];
_b = _s[_t];
_s[_t-2] = _a;
_a = _s[_t-1];
_r = _s[_t-3];
return _p(_bb4_set_2d_attr);
},4,1);

_j(_bb4_set_2d_attr = () => {
_n = 3;
_t -= 4;
return _check_procedure(_s[_t+2])();
});



_m(_bb1_append_2d_child = () => {
if (_n !== 2) {
return _w(_bb1_append_2d_child);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_s[_t+3] = _b;
_a = _cst42__limina;
_t += 3;
return _p(_bb2_append_2d_child);
},-1,_i("append-child"),!1,!0);

_j(_bb2_append_2d_child = () => {
_r = _bb3_append_2d_child;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_append_2d_child = () => {
_b = _s[_t-1];
_s[_t-1] = _a;
_a = _s[_t];
_r = _s[_t-2];
return _p(_bb4_append_2d_child);
},3,1);

_j(_bb4_append_2d_child = () => {
_n = 2;
_t -= 3;
return _check_procedure(_s[_t+2])();
});



_m(_bb1_load_2d_js = () => {
if (_n === 1) {
_b = !1;
} else {
if (_n !== 2) {
return _w(_bb1_load_2d_js);
}
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_s[_t+3] = _b;
_a = _cst31__limina;
_t += 3;
return _p(_bb2_load_2d_js);
},-1,_i("load-js"),!1,!0);

_j(_bb2_load_2d_js = () => {
_r = _bb3_load_2d_js;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_load_2d_js = () => {
_s[_t+1] = _a;
_a = _cst76__limina;
_r = _bb4_load_2d_js;
_n = 1;
return _check_procedure(_s[_t+1])();
},3,1);

_k(_bb4_load_2d_js = () => {
_s[_t+1] = _a;
_a = _cst34__limina;
_r = _bb5_load_2d_js;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},3,1);

_k(_bb5_load_2d_js = () => {
_c = _s[_t];
_b = _cst77__limina;
_s[_t+1] = _a;
_a = _cst78__limina;
_r = _bb6_load_2d_js;
_n = 3;
return _check_procedure(_s[_t+1])();
},4,1);

_k(_bb6_load_2d_js = () => {
_a = _s[_t-1];
if (!(_a === !1)) {
return _bb8_load_2d_js();
} else {
return _bb25_load_2d_js();
}
},4,1);

_j(_bb8_load_2d_js = () => {
_s[_t+1] = _a;
_a = _s[_t-1];
if (!(_a === !1)) {
++_t;
return _bb9_load_2d_js();
} else {
++_t;
return _bb20_load_2d_js();
}
});

_j(_bb25_load_2d_js = () => {
_r = _bb26_load_2d_js;
_n = 0;
return _u(_g["make-mutex"],_cst79__limina)();
});

_j(_bb9_load_2d_js = () => {
_a = _cst34__limina;
_r = _bb10_load_2d_js;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_j(_bb20_load_2d_js = () => {
_a = _cst80__limina;
_r = _bb21_load_2d_js;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb26_load_2d_js = () => {
_s[_t+1] = _a;
_r = _bb7_load_2d_js;
_n = 1;
++_t;
return _u(_g["mutex-lock!"],_cst82__limina)();
},4,1);

_k(_bb10_load_2d_js = () => {
_c = _s[_t-1];
_b = _s[_t-3];
_s[_t-3] = _a;
_a = _cst83__limina;
_r = _bb11_load_2d_js;
_n = 3;
return _check_procedure(_s[_t-3])();
},5,1);

_k(_bb21_load_2d_js = () => {
var closure0 = _closure_alloc([_bb23_load_2d_js,_s[_t]]);
_s[_t+1] = closure0;
_b = _s[_t+1];
_s[_t+1] = _a;
_a = _s[_t-1];
_r = _bb22_load_2d_js;
_n = 2;
return _check_procedure(_s[_t+1])();
},5,1);

_k(_bb7_load_2d_js = () => {
_a = _s[_t];
--_t;
return _bb8_load_2d_js();
},5,1);

_k(_bb11_load_2d_js = () => {
_a = _cst84__limina;
_r = _bb12_load_2d_js;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},5,1);

_l(_bb23_load_2d_js = () => {
if (_n === 0) {
_a = null;
} else {
if (!_build_rest(0)) {
return _w(_d);
}
}
_a = _d(!0)[1];
return _p(_bb24_load_2d_js);
},1);

_k(_bb22_load_2d_js = () => {
return _bb9_load_2d_js();
},5,1);

_k(_bb12_load_2d_js = () => {
_r = _bb13_load_2d_js;
_n = 0;
return _check_procedure(_a);
},5,1);

_j(_bb24_load_2d_js = () => {
_n = 1;
return _u(_g["mutex-unlock!"],_cst86__limina)();
});

_k(_bb13_load_2d_js = () => {
_s[_t-3] = _a;
_a = _cst42__limina;
_r = _bb14_load_2d_js;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},5,1);

_k(_bb14_load_2d_js = () => {
_b = _s[_t-3];
_s[_t-3] = _a;
_a = _s[_t-1];
_r = _bb15_load_2d_js;
_n = 2;
return _check_procedure(_s[_t-3])();
},5,1);

_k(_bb15_load_2d_js = () => {
_a = _s[_t-2];
if (!(_a === !1)) {
return _bb19_load_2d_js();
} else {
return _bb16_load_2d_js();
}
},5,1);

_j(_bb19_load_2d_js = () => {
_t -= 5;
return _s[_t+1]();
});

_j(_bb16_load_2d_js = () => {
_a = _s[_t];
_r = _bb17_load_2d_js;
_n = 1;
return _u(_g["mutex-lock!"],_cst82__limina)();
});

_k(_bb17_load_2d_js = () => {
_a = _s[_t];
_r = _s[_t-4];
return _p(_bb18_load_2d_js);
},5,1);

_j(_bb18_load_2d_js = () => {
_n = 1;
_t -= 5;
return _u(_g["mutex-unlock!"],_cst86__limina)();
});



_m(_bb1__25_object_2d_keys = () => {
if (_n !== 1) {
return _w(_bb1__25_object_2d_keys);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_a = _cst87__limina;
_t += 2;
return _p(_bb2__25_object_2d_keys);
},-1,_i("%object-keys"),!1,!0);

_j(_bb2__25_object_2d_keys = () => {
_r = _bb3__25_object_2d_keys;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3__25_object_2d_keys = () => {
_s[_t+1] = _a;
_a = _s[_t];
_r = _bb4__25_object_2d_keys;
_n = 1;
--_t;
return _check_procedure(_s[_t+2])();
},2,1);

_k(_bb4__25_object_2d_keys = () => {
_r = _s[_t];
return _p(_bb5__25_object_2d_keys);
},1,1);

_j(_bb5__25_object_2d_keys = () => {
_n = 1;
--_t;
return _e["vector->list"]();
});



_m(_bb1__25_object_2d_values = () => {
if (_n !== 1) {
return _w(_bb1__25_object_2d_values);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_a = _cst90__limina;
_t += 2;
return _p(_bb2__25_object_2d_values);
},-1,_i("%object-values"),!1,!0);

_j(_bb2__25_object_2d_values = () => {
_r = _bb3__25_object_2d_values;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3__25_object_2d_values = () => {
_s[_t+1] = _a;
_a = _s[_t];
_r = _bb4__25_object_2d_values;
_n = 1;
--_t;
return _check_procedure(_s[_t+2])();
},2,1);

_k(_bb4__25_object_2d_values = () => {
_r = _s[_t];
return _p(_bb5__25_object_2d_values);
},1,1);

_j(_bb5__25_object_2d_values = () => {
_n = 1;
--_t;
return _e["vector->list"]();
});



_m(_bb1__25_object_2d_entries = () => {
if (_n !== 1) {
return _w(_bb1__25_object_2d_entries);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_a = _cst92__limina;
_t += 2;
return _p(_bb2__25_object_2d_entries);
},-1,_i("%object-entries"),!1,!0);

_j(_bb2__25_object_2d_entries = () => {
_r = _bb3__25_object_2d_entries;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3__25_object_2d_entries = () => {
_s[_t+1] = _a;
_a = _s[_t];
_r = _bb4__25_object_2d_entries;
_n = 1;
--_t;
return _check_procedure(_s[_t+2])();
},2,1);

_k(_bb4__25_object_2d_entries = () => {
_r = _bb5__25_object_2d_entries;
_n = 1;
return _e["vector->list"]();
},1,1);

_k(_bb5__25_object_2d_entries = () => {
_b = _a;
_a = _e["vector->list"];
_r = _s[_t];
return _p(_bb6__25_object_2d_entries);
},1,1);

_j(_bb6__25_object_2d_entries = () => {
_n = 2;
--_t;
return _u(_g["srfi/1#map"],_cst94__limina)();
});



_m(_bb1__25_object_3f_ = () => {
if (_n !== 1) {
return _w(_bb1__25_object_3f_);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_a = _cst95__limina;
_t += 2;
return _p(_bb2__25_object_3f_);
},-1,_i("%object?"),!1,!0);

_j(_bb2__25_object_3f_ = () => {
_r = _bb3__25_object_3f_;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3__25_object_3f_ = () => {
_b = _s[_t];
_s[_t+1] = _a;
_a = _s[_t];
_r = _s[_t-1];
++_t;
return _p(_bb4__25_object_3f_);
},2,1);

_j(_bb4__25_object_3f_ = () => {
_n = 2;
_t -= 3;
return _check_procedure(_s[_t+3])();
});



_m(_bb1__25_shallow_2d_object_2d__3e_alist = () => {
if (_n !== 1) {
return _w(_bb1__25_shallow_2d_object_2d__3e_alist);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_a = _cst92__limina;
_t += 2;
return _p(_bb2__25_shallow_2d_object_2d__3e_alist);
},-1,_i("%shallow-object->alist"),!1,!0);

_j(_bb2__25_shallow_2d_object_2d__3e_alist = () => {
_r = _bb3__25_shallow_2d_object_2d__3e_alist;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3__25_shallow_2d_object_2d__3e_alist = () => {
_s[_t+1] = _a;
_a = _s[_t];
_r = _bb4__25_shallow_2d_object_2d__3e_alist;
_n = 1;
--_t;
return _check_procedure(_s[_t+2])();
},2,1);

_k(_bb4__25_shallow_2d_object_2d__3e_alist = () => {
_r = _bb5__25_shallow_2d_object_2d__3e_alist;
_n = 1;
return _e["vector->list"]();
},1,1);

_k(_bb5__25_shallow_2d_object_2d__3e_alist = () => {
_b = _a;
_a = _e["vector->list"];
_r = _s[_t];
return _p(_bb6__25_shallow_2d_object_2d__3e_alist);
},1,1);

_j(_bb6__25_shallow_2d_object_2d__3e_alist = () => {
_n = 2;
--_t;
return _u(_g["srfi/1#map"],_cst94__limina)();
});



_m(_bb1__25_deep_2d_object_2d__3e_alist = () => {
if (_n !== 1) {
return _w(_bb1__25_deep_2d_object_2d__3e_alist);
}
return _bb4__25_deep_2d_object_2d__3e_alist();
},-1,_i("%deep-object->alist"),!1,!0);

_j(_bb4__25_deep_2d_object_2d__3e_alist = () => {
_s[_t+1] = _bb11__25_deep_2d_object_2d__3e_alist;
_s[_t+2] = _r;
_s[_t+3] = _a;
_a = _cst92__limina;
_t += 3;
return _p(_bb5__25_deep_2d_object_2d__3e_alist);
});

_l(_bb11__25_deep_2d_object_2d__3e_alist = () => {
if (_n !== 1) {
return _w(_bb11__25_deep_2d_object_2d__3e_alist);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_t += 2;
return _p(_bb12__25_deep_2d_object_2d__3e_alist);
},-1);

_j(_bb5__25_deep_2d_object_2d__3e_alist = () => {
_r = _bb6__25_deep_2d_object_2d__3e_alist;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_j(_bb12__25_deep_2d_object_2d__3e_alist = () => {
_r = _bb13__25_deep_2d_object_2d__3e_alist;
_n = 1;
return _u(_g["srfi/1#car"],_cst97__limina)();
});

_k(_bb6__25_deep_2d_object_2d__3e_alist = () => {
_s[_t+1] = _a;
_a = _s[_t];
_r = _bb7__25_deep_2d_object_2d__3e_alist;
_n = 1;
--_t;
return _check_procedure(_s[_t+2])();
},3,2);

_k(_bb13__25_deep_2d_object_2d__3e_alist = () => {
_s[_t+1] = _a;
_a = _s[_t];
_r = _bb14__25_deep_2d_object_2d__3e_alist;
_n = 1;
++_t;
return _u(_g["srfi/1#cadr"],_cst98__limina)();
},2,1);

_k(_bb7__25_deep_2d_object_2d__3e_alist = () => {
_r = _bb8__25_deep_2d_object_2d__3e_alist;
_n = 1;
return _e["vector->list"]();
},2,2);

_k(_bb14__25_deep_2d_object_2d__3e_alist = () => {
_s[_t-1] = _a;
_a = _cst95__limina;
_r = _bb15__25_deep_2d_object_2d__3e_alist;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},3,1);

_k(_bb8__25_deep_2d_object_2d__3e_alist = () => {
_b = _a;
_a = _e["vector->list"];
_r = _bb9__25_deep_2d_object_2d__3e_alist;
_n = 2;
return _u(_g["srfi/1#map"],_cst94__limina)();
},2,2);

_k(_bb15__25_deep_2d_object_2d__3e_alist = () => {
_b = _s[_t-1];
_s[_t+1] = _a;
_a = _s[_t-1];
_r = _bb16__25_deep_2d_object_2d__3e_alist;
_n = 2;
return _check_procedure(_s[_t+1])();
},3,1);

_k(_bb9__25_deep_2d_object_2d__3e_alist = () => {
_b = _a;
_r = _s[_t];
_a = _s[_t-1];
return _p(_bb10__25_deep_2d_object_2d__3e_alist);
},2,2);

_k(_bb16__25_deep_2d_object_2d__3e_alist = () => {
if (!(_a === !1)) {
return _bb21__25_deep_2d_object_2d__3e_alist();
} else {
return _bb17__25_deep_2d_object_2d__3e_alist();
}
},3,1);

_j(_bb10__25_deep_2d_object_2d__3e_alist = () => {
_n = 2;
_t -= 2;
return _u(_g["srfi/1#map"],_cst94__limina)();
});

_j(_bb21__25_deep_2d_object_2d__3e_alist = () => {
_a = _s[_t-1];
_r = _bb2__25_deep_2d_object_2d__3e_alist;
_n = 1;
return _u(_g["srfi/1#null?"],_cst99__limina)();
});

_j(_bb17__25_deep_2d_object_2d__3e_alist = () => {
_a = _s[_t-1];
return _bb19__25_deep_2d_object_2d__3e_alist();
});

_k(_bb2__25_deep_2d_object_2d__3e_alist = () => {
if (!(_a === !1)) {
return _bb17__25_deep_2d_object_2d__3e_alist();
} else {
return _bb3__25_deep_2d_object_2d__3e_alist();
}
},3,1);

_j(_bb19__25_deep_2d_object_2d__3e_alist = () => {
_b = _a;
_a = _s[_t];
_r = _s[_t-2];
return _p(_bb20__25_deep_2d_object_2d__3e_alist);
});

_j(_bb3__25_deep_2d_object_2d__3e_alist = () => {
_a = _s[_t-1];
_r = _bb18__25_deep_2d_object_2d__3e_alist;
return _bb4__25_deep_2d_object_2d__3e_alist();
});

_j(_bb20__25_deep_2d_object_2d__3e_alist = () => {
_n = 2;
_t -= 3;
return _u(_g["srfi/1#list"],_cst100__limina)();
});

_k(_bb18__25_deep_2d_object_2d__3e_alist = () => {
return _bb19__25_deep_2d_object_2d__3e_alist();
},3,1);



_m(_bb1__25_object_2d__3e_hash_2d_table = () => {
if (_n !== 1) {
return _w(_bb1__25_object_2d__3e_hash_2d_table);
}
_s[_t+1] = _r;
++_t;
return _p(_bb2__25_object_2d__3e_hash_2d_table);
},-1,_i("%object->hash-table"),!1,!0);

_j(_bb2__25_object_2d__3e_hash_2d_table = () => {
_r = _bb3__25_object_2d__3e_hash_2d_table;
_n = 1;
return _bb1__25_deep_2d_object_2d__3e_alist();
});

_k(_bb3__25_object_2d__3e_hash_2d_table = () => {
_r = _s[_t];
return _p(_bb4__25_object_2d__3e_hash_2d_table);
},1,1);

_j(_bb4__25_object_2d__3e_hash_2d_table = () => {
_n = 1;
--_t;
return _u(_g["srfi/69#alist->hash-table"],_cst101__limina)();
});



_m(_bb1_import_2d_from = () => {
if (_n !== 3) {
return _w(_bb1_import_2d_from);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_s[_t+3] = _c;
_s[_t+4] = _b;
_b = _c;
_a = _s[_t+4];
_r = _bb2_import_2d_from;
_n = 2;
_t += 3;
return _e["string-append"]();
},-1,_i("import-from"),!1,!0);

_k(_bb2_import_2d_from = () => {
_s[_t+1] = _a;
_a = _cst103__limina;
++_t;
return _p(_bb3_import_2d_from);
},3,1);

_j(_bb3_import_2d_from = () => {
_r = _bb4_import_2d_from;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb4_import_2d_from = () => {
_c = _s[_t-1];
_b = _s[_t-2];
_s[_t-2] = _a;
_a = _s[_t];
_r = _s[_t-3];
return _p(_bb5_import_2d_from);
},4,1);

_j(_bb5_import_2d_from = () => {
_n = 3;
_t -= 4;
return _check_procedure(_s[_t+2])();
});



_m(_bb1_intern_2d_from_2d_module = () => {
if (_n !== 2) {
return _w(_bb1_intern_2d_from_2d_module);
}
var closure0 = _closure_alloc([_bb5_intern_2d_from_2d_module,_a,_b]);
_s[_t+1] = closure0;
_s[_t+2] = _r;
_t += 2;
return _p(_bb2_intern_2d_from_2d_module);
},-1,_i("intern-from-module"),!1,!0);

_l(_bb5_intern_2d_from_2d_module = () => {
if (_n !== 1) {
return _w(_d);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_s[_t+3] = _d;
_t += 3;
return _p(_bb6_intern_2d_from_2d_module);
},2);

_j(_bb2_intern_2d_from_2d_module = () => {
_r = _bb3_intern_2d_from_2d_module;
_n = 1;
return _u(_g["entries"],_cst105__limina)();
});

_j(_bb6_intern_2d_from_2d_module = () => {
_r = _bb7_intern_2d_from_2d_module;
_n = 1;
return _u(_g["srfi/1#car"],_cst97__limina)();
});

_k(_bb3_intern_2d_from_2d_module = () => {
_b = _a;
_r = _s[_t];
_a = _s[_t-1];
return _p(_bb4_intern_2d_from_2d_module);
},2,2);

_k(_bb7_intern_2d_from_2d_module = () => {
_s[_t+1] = _a;
_a = _s[_t-1];
_r = _bb8_intern_2d_from_2d_module;
_n = 1;
++_t;
return _u(_g["srfi/1#cadr"],_cst98__limina)();
},3,1);

_j(_bb4_intern_2d_from_2d_module = () => {
_n = 2;
_t -= 2;
return _u(_g["srfi/1#map"],_cst94__limina)();
});

_k(_bb8_intern_2d_from_2d_module = () => {
_b = _s[_t];
_a = _s[_t-1](!0)[2];
_r = _bb9_intern_2d_from_2d_module;
_n = 2;
return _e["string-append"]();
},4,1);

_k(_bb9_intern_2d_from_2d_module = () => {
_b = _s[_t];
_a = _s[_t-1](!0)[2];
_r = _bb10_intern_2d_from_2d_module;
_n = 2;
return _e["string-append"]();
},4,1);

_k(_bb10_intern_2d_from_2d_module = () => {
_s[_t-2] = _a;
_a = _cst103__limina;
_r = _bb11_intern_2d_from_2d_module;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},4,1);

_k(_bb11_intern_2d_from_2d_module = () => {
_c = _s[_t];
_b = _s[_t-1](!0)[1];
_s[_t-1] = _a;
_a = _s[_t-2];
_r = _s[_t-3];
return _p(_bb12_intern_2d_from_2d_module);
},4,1);

_j(_bb12_intern_2d_from_2d_module = () => {
_n = 3;
_t -= 4;
return _check_procedure(_s[_t+3])();
});



_m(_bb1_box = () => {
if (_n !== 3) {
return _w(_bb1_box);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_s[_t+3] = _b;
_s[_t+4] = _c;
_a = _cst106__limina;
_t += 4;
return _p(_bb2_box);
},-1,_i("box"),!1,!0);

_j(_bb2_box = () => {
_r = _bb3_box;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_box = () => {
_c = _s[_t];
_b = _s[_t-1];
_s[_t-1] = _a;
_a = _s[_t-2];
_r = _bb4_box;
_n = 3;
_t -= 3;
return _check_procedure(_s[_t+2])();
},4,1);

_k(_bb4_box = () => {
_s[_t+1] = _a;
_a = _cst108__limina;
_r = _bb5_box;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},1,1);

_k(_bb5_box = () => {
_r = _bb6_box;
_n = 0;
return _check_procedure(_a);
},2,1);

_k(_bb6_box = () => {
_s[_t+1] = _a;
_a = _cst110__limina;
_r = _bb7_box;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},2,1);

_k(_bb7_box = () => {
_b = _s[_t];
_s[_t+1] = _a;
_a = _s[_t-1];
_r = _bb8_box;
_n = 2;
return _check_procedure(_s[_t+1])();
},3,1);

_k(_bb8_box = () => {
_s[_t-1] = _a;
_a = _cst66__limina;
_r = _bb9_box;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},3,1);

_k(_bb9_box = () => {
_s[_t+1] = _a;
_a = _s[_t];
_b = _cst112__limina;
_r = _bb10_box;
_n = 2;
return _check_procedure(_s[_t+1])();
},3,1);

_k(_bb10_box = () => {
_c = 3359812;
_b = _cst113__limina;
_r = _bb21_box;
_n = 3;
return _bb12_box();
},3,1);

_l(_bb12_box = () => {
if (_n === 2) {
_c = null;
} else {
if (!_build_rest(2)) {
return _w(_bb12_box);
}
}
_s[_t+1] = _a;
_s[_t+2] = _r;
_s[_t+3] = _a;
_s[_t+4] = _b;
_s[_t+5] = _c;
_a = _cst70__limina;
_t += 5;
return _p(_bb13_box);
},-1);

_k(_bb21_box = () => {
_a = _cst21__limina;
_r = _bb22_box;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},3,1);

_j(_bb13_box = () => {
_r = _bb14_box;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb22_box = () => {
_s[_t+1] = _a;
_a = _s[_t];
_c = _F(0.3);
_b = _cst114__limina;
_r = _bb23_box;
_n = 3;
return _check_procedure(_s[_t+1])();
},3,1);

_k(_bb14_box = () => {
_c = _s[_t-1];
_b = _s[_t-2];
_s[_t-2] = _a;
_a = _s[_t];
_r = _s[_t-3];
return _p(_bb15_box);
},5,2);

_k(_bb23_box = () => {
_a = _cst21__limina;
_r = _bb24_box;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},3,1);

_j(_bb15_box = () => {
_n = 4;
_t -= 4;
return _check_procedure(_s[_t+2])();
});

_k(_bb24_box = () => {
_s[_t+1] = _a;
_a = _s[_t];
_c = !0;
_b = _cst115__limina;
_r = _bb25_box;
_n = 3;
--_t;
return _check_procedure(_s[_t+2])();
},3,1);

_k(_bb25_box = () => {
_a = _cst66__limina;
_r = _bb26_box;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},2,1);

_k(_bb26_box = () => {
_s[_t+1] = _a;
_a = _s[_t];
_b = _cst116__limina;
_r = _bb11_box;
_n = 2;
return _check_procedure(_s[_t+1])();
},2,1);

_k(_bb11_box = () => {
_s[_t+1] = _a;
_s[_t+2] = _cst117__limina;
_c = 0;
_b = 1;
_a = 2;
_r = _bb16_box;
_n = 5;
_t += 2;
return _bb12_box();
},2,1);

_k(_bb16_box = () => {
_a = _cst66__limina;
_r = _bb17_box;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},2,1);

_k(_bb17_box = () => {
_s[_t+1] = _a;
_a = _s[_t];
_b = _cst118__limina;
_r = _bb18_box;
_n = 2;
return _check_procedure(_s[_t+1])();
},2,1);

_k(_bb18_box = () => {
_s[_t+1] = _a;
_s[_t+2] = _cst117__limina;
_s[_t+3] = 10;
_c = 10;
_b = 10;
_a = 10;
_r = _bb20_box;
_n = 6;
_t += 3;
return _bb19_box();
},2,1);

_l(_bb19_box = () => {
if (_n === 2) {
_c = null;
} else {
if (!_build_rest(2)) {
return _w(_bb19_box);
}
}
_s[_t+1] = _a;
_s[_t+2] = _r;
_s[_t+3] = _a;
_s[_t+4] = _b;
_s[_t+5] = _c;
_a = _cst57__limina;
_t += 5;
return _p(_bb13_box);
},-1);

_k(_bb20_box = () => {
_a = _s[_t];
_t -= 2;
return _s[_t+1]();
},2,1);



_m(_bb1_vec3 = () => {
if (_n === 0) {
_a = 0;
_b = 0;
_c = 0;
} else {
if (_n === 1) {
_b = 0;
_c = 0;
} else {
if (_n === 2) {
_c = 0;
} else {
if (_n !== 3) {
return _w(_bb1_vec3);
}
}
}
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_s[_t+3] = _b;
_s[_t+4] = _c;
_a = _cst119__limina;
_t += 4;
return _p(_bb2_vec3);
},-1,_i("vec3"),!1,!0);

_j(_bb2_vec3 = () => {
_r = _bb3_vec3;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_vec3 = () => {
_c = _s[_t];
_b = _s[_t-1];
_s[_t-1] = _a;
_a = _s[_t-2];
_r = _s[_t-3];
return _p(_bb4_vec3);
},4,1);

_j(_bb4_vec3 = () => {
_n = 3;
_t -= 4;
return _check_procedure(_s[_t+3])();
});



_m(_bb1_kball = () => {
if (_n !== 0) {
return _w(_bb1_kball);
}
_s[_t+1] = _r;
_a = _cst121__limina;
++_t;
return _p(_bb2_kball);
},-1,_i("kball"),!1,!0);

_j(_bb2_kball = () => {
_r = _bb3_kball;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_kball = () => {
_c = 12;
_b = 12;
_s[_t+1] = _a;
_a = _g["r"];
_r = _bb4_kball;
_n = 3;
return _check_procedure(_s[_t+1])();
},1,1);

_k(_bb4_kball = () => {
_s[_t+1] = _a;
_a = _cst123__limina;
_r = _bb5_kball;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},1,1);

_k(_bb5_kball = () => {
_b = _host2scm({ color:0x404444 });
_s[_t+1] = _a;
_a = _b;
_r = _bb6_kball;
_n = 1;
return _check_procedure(_s[_t+1])();
},2,1);

_k(_bb6_kball = () => {
_s[_t+1] = _a;
_a = _cst125__limina;
_r = _bb7_kball;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},2,1);

_k(_bb7_kball = () => {
_b = _s[_t];
_s[_t+1] = _a;
_a = _s[_t-1];
_r = _bb8_kball;
_n = 2;
return _check_procedure(_s[_t+1])();
},3,1);

_k(_bb8_kball = () => {
_s[_t-1] = _a;
_a = _cst21__limina;
_r = _bb9_kball;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},3,1);

_k(_bb9_kball = () => {
_s[_t+1] = _a;
_a = _s[_t];
_c = !0;
_b = _cst127__limina;
_r = _bb10_kball;
_n = 3;
--_t;
return _check_procedure(_s[_t+2])();
},3,1);

_k(_bb10_kball = () => {
_a = _cst21__limina;
_r = _bb11_kball;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},2,1);

_k(_bb11_kball = () => {
_s[_t+1] = _a;
_a = _s[_t];
_c = !0;
_b = _cst128__limina;
_r = _bb12_kball;
_n = 3;
return _check_procedure(_s[_t+1])();
},2,1);

_k(_bb12_kball = () => {
_a = _cst21__limina;
_r = _bb13_kball;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},2,1);

_k(_bb13_kball = () => {
_s[_t+1] = _a;
_a = _s[_t];
_c = !0;
_b = _cst129__limina;
_r = _bb14_kball;
_n = 3;
return _check_procedure(_s[_t+1])();
},2,1);

_k(_bb14_kball = () => {
_a = _cst21__limina;
_r = _bb15_kball;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},2,1);

_k(_bb15_kball = () => {
_s[_t+1] = _a;
_a = _s[_t];
_c = _cst130__limina;
_b = _cst131__limina;
_r = _bb16_kball;
_n = 3;
return _check_procedure(_s[_t+1])();
},2,1);

_k(_bb16_kball = () => {
_a = _s[_t];
_t -= 2;
return _s[_t+1]();
},2,1);



_m(_bb1_kbox = () => {
if (_n !== 0) {
return _w(_bb1_kbox);
}
_s[_t+1] = _r;
++_t;
return _p(_bb2_kbox);
},-1,_i("kbox"),!1,!0);

_j(_bb2_kbox = () => {
_r = _bb3_kbox;
_n = 0;
return _bb1_pbox();
});

_k(_bb3_kbox = () => {
_s[_t+1] = _a;
_a = _cst21__limina;
_r = _bb4_kbox;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},1,1);

_k(_bb4_kbox = () => {
_s[_t+1] = _a;
_a = _s[_t];
_c = _cst132__limina;
_b = _cst131__limina;
_r = _bb5_kbox;
_n = 3;
return _check_procedure(_s[_t+1])();
},2,1);

_k(_bb5_kbox = () => {
_a = _s[_t];
_t -= 2;
return _s[_t+1]();
},2,1);



_m(_bb1_pbox = () => {
if (_n !== 0) {
return _w(_bb1_pbox);
}
_s[_t+1] = _r;
_a = _cst133__limina;
++_t;
return _p(_bb2_pbox);
},-1,_i("pbox"),!1,!0);

_j(_bb2_pbox = () => {
_r = _bb3_pbox;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_pbox = () => {
_c = 1;
_b = 1;
_s[_t+1] = _a;
_a = 1;
_r = _bb4_pbox;
_n = 3;
return _check_procedure(_s[_t+1])();
},1,1);

_k(_bb4_pbox = () => {
_s[_t+1] = _a;
_a = _cst135__limina;
_r = _bb5_pbox;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},1,1);

_k(_bb5_pbox = () => {
_b = _host2scm({color: 0x445555, opacity: 0.8,
                             transparent: true});
_s[_t+1] = _a;
_a = _b;
_r = _bb6_pbox;
_n = 1;
return _check_procedure(_s[_t+1])();
},2,1);

_k(_bb6_pbox = () => {
_s[_t+1] = _a;
_a = _cst137__limina;
_r = _bb7_pbox;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},2,1);

_k(_bb7_pbox = () => {
_b = _s[_t];
_s[_t] = _a;
_a = _s[_t-1];
_r = _bb8_pbox;
_n = 2;
_t -= 2;
return _check_procedure(_s[_t+2])();
},3,1);

_k(_bb8_pbox = () => {
_s[_t+1] = _a;
_a = _cst21__limina;
_r = _bb9_pbox;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},1,1);

_k(_bb9_pbox = () => {
_s[_t+1] = _a;
_a = _s[_t];
_c = !0;
_b = _cst128__limina;
_r = _bb10_pbox;
_n = 3;
return _check_procedure(_s[_t+1])();
},2,1);

_k(_bb10_pbox = () => {
_a = _cst21__limina;
_r = _bb11_pbox;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},2,1);

_k(_bb11_pbox = () => {
_s[_t+1] = _a;
_a = _s[_t];
_c = !0;
_b = _cst129__limina;
_r = _bb12_pbox;
_n = 3;
return _check_procedure(_s[_t+1])();
},2,1);

_k(_bb12_pbox = () => {
_a = _cst21__limina;
_r = _bb13_pbox;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},2,1);

_k(_bb13_pbox = () => {
_s[_t+1] = _a;
_a = _s[_t];
_c = _cst139__limina;
_b = _cst131__limina;
_r = _bb14_pbox;
_n = 3;
return _check_procedure(_s[_t+1])();
},2,1);

_k(_bb14_pbox = () => {
_a = _s[_t];
_t -= 2;
return _s[_t+1]();
},2,1);



_m(_bb1_qbox = () => {
if (_n !== 0) {
return _w(_bb1_qbox);
}
_s[_t+1] = _r;
_a = _cst140__limina;
++_t;
return _p(_bb2_qbox);
},-1,_i("qbox"),!1,!0);

_j(_bb2_qbox = () => {
_r = _bb3_qbox;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_qbox = () => {
_c = _F(0.05);
_b = _F(0.05);
_s[_t+1] = _a;
_a = 1;
_r = _bb4_qbox;
_n = 3;
return _check_procedure(_s[_t+1])();
},1,1);

_k(_bb4_qbox = () => {
_s[_t+1] = _a;
_a = _cst142__limina;
_r = _bb5_qbox;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},1,1);

_k(_bb5_qbox = () => {
_b = _host2scm({color: 0x00ff00, opacity: 0.5, transparent: true});
_s[_t+1] = _a;
_a = _b;
_r = _bb6_qbox;
_n = 1;
return _check_procedure(_s[_t+1])();
},2,1);

_k(_bb6_qbox = () => {
_s[_t+1] = _a;
_a = _cst144__limina;
_r = _bb7_qbox;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},2,1);

_k(_bb7_qbox = () => {
_b = _s[_t];
_s[_t] = _a;
_a = _s[_t-1];
_r = _bb8_qbox;
_n = 2;
_t -= 2;
return _check_procedure(_s[_t+2])();
},3,1);

_k(_bb8_qbox = () => {
_s[_t+1] = _a;
_a = _cst21__limina;
_r = _bb9_qbox;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},1,1);

_k(_bb9_qbox = () => {
_s[_t+1] = _a;
_a = _s[_t];
_c = _cst146__limina;
_b = _cst131__limina;
_r = _bb10_qbox;
_n = 3;
return _check_procedure(_s[_t+1])();
},2,1);

_k(_bb10_qbox = () => {
_a = _s[_t];
_t -= 2;
return _s[_t+1]();
},2,1);



_m(_bb1_dipshit = () => {
if (_n !== 0) {
return _w(_bb1_dipshit);
}
_s[_t+1] = _r;
++_t;
return _p(_bb2_dipshit);
},-1,_i("dipshit"),!1,!0);

_j(_bb2_dipshit = () => {
_r = _bb3_dipshit;
_n = 0;
return _bb1_htmlbox();
});

_k(_bb3_dipshit = () => {
var closure0 = _closure_alloc([_bb5_dipshit,_a]);
_s[_t+1] = closure0;
_s[_t+2] = _a;
_a = _s[_t+1];
_r = _bb4_dipshit;
_n = 1;
_t += 2;
return _u(_g["later"],_cst147__limina)();
},1,1);

_l(_bb5_dipshit = () => {
if (_n !== 0) {
return _w(_d);
}
_s[_t+1] = _r;
_s[_t+2] = _d;
_a = _cst66__limina;
_t += 2;
return _p(_bb6_dipshit);
},1);

_k(_bb4_dipshit = () => {
_a = _s[_t];
_t -= 3;
return _s[_t+1]();
},3,1);

_j(_bb6_dipshit = () => {
_r = _bb7_dipshit;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb7_dipshit = () => {
_s[_t+1] = _a;
_a = _s[_t](!0)[1];
_b = _cst148__limina;
_r = _bb8_dipshit;
_n = 2;
--_t;
return _check_procedure(_s[_t+2])();
},2,1);

_k(_bb8_dipshit = () => {
_s[_t+1] = _a;
_a = _cst149__limina;
_r = _s[_t];
++_t;
return _p(_bb9_dipshit);
},1,1);

_j(_bb9_dipshit = () => {
_n = 1;
_t -= 2;
return _check_procedure(_s[_t+2])();
});



_m(_bb1_htmlbox = () => {
if (_n !== 0) {
return _w(_bb1_htmlbox);
}
_s[_t+1] = _r;
_a = _cst31__limina;
++_t;
return _p(_bb2_htmlbox);
},-1,_i("htmlbox"),!1,!0);

_j(_bb2_htmlbox = () => {
_r = _bb3_htmlbox;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_htmlbox = () => {
_s[_t+1] = _a;
_a = _cst150__limina;
_r = _bb4_htmlbox;
_n = 1;
return _check_procedure(_s[_t+1])();
},1,1);

_k(_bb4_htmlbox = () => {
_s[_t+1] = _a;
_c = _cst151__limina;
_b = _cst152__limina;
_r = _bb18_htmlbox;
_n = 3;
++_t;
return _bb5_htmlbox();
},1,1);

_l(_bb5_htmlbox = () => {
if (_n === 2) {
_c = null;
} else {
if (!_build_rest(2)) {
return _w(_bb5_htmlbox);
}
}
_s[_t+1] = _a;
_s[_t+2] = _r;
_s[_t+3] = _a;
_s[_t+4] = _b;
_s[_t+5] = _c;
_a = _cst70__limina;
_t += 5;
return _p(_bb10_htmlbox);
},-1);

_k(_bb18_htmlbox = () => {
_s[_t+1] = _a;
_a = _cst153__limina;
_r = _bb19_htmlbox;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},2,1);

_j(_bb10_htmlbox = () => {
_r = _bb11_htmlbox;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb19_htmlbox = () => {
_s[_t+1] = _a;
_a = _s[_t-1];
_r = _bb20_htmlbox;
_n = 1;
return _check_procedure(_s[_t+1])();
},3,1);

_k(_bb11_htmlbox = () => {
_c = _s[_t-1];
_b = _s[_t-2];
_s[_t-2] = _a;
_a = _s[_t];
_r = _s[_t-3];
return _p(_bb12_htmlbox);
},5,2);

_k(_bb20_htmlbox = () => {
_s[_t+1] = _a;
_a = _cst155__limina;
_r = _bb21_htmlbox;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},3,1);

_j(_bb12_htmlbox = () => {
_n = 4;
_t -= 4;
return _check_procedure(_s[_t+2])();
});

_k(_bb21_htmlbox = () => {
_c = _F(0.01);
_b = 1;
_s[_t+1] = _a;
_a = 1;
_r = _bb22_htmlbox;
_n = 3;
return _check_procedure(_s[_t+1])();
},4,1);

_k(_bb22_htmlbox = () => {
_s[_t+1] = _a;
_a = _cst157__limina;
_r = _bb23_htmlbox;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},4,1);

_k(_bb23_htmlbox = () => {
_b = _host2scm({transparent: true, opacity: 1});
_s[_t+1] = _a;
_a = _b;
_r = _bb24_htmlbox;
_n = 1;
return _check_procedure(_s[_t+1])();
},5,1);

_k(_bb24_htmlbox = () => {
_s[_t+1] = _a;
_a = _cst159__limina;
_r = _bb25_htmlbox;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},5,1);

_k(_bb25_htmlbox = () => {
_b = _s[_t];
_s[_t+1] = _a;
_a = _s[_t-1];
_r = _bb26_htmlbox;
_n = 2;
return _check_procedure(_s[_t+1])();
},6,1);

_k(_bb26_htmlbox = () => {
var closure0 = _closure_alloc([_bb52_htmlbox,_s[_t-2]]);
_s[_t+1] = closure0;
var closure1 = _closure_alloc([_bb6_htmlbox,_s[_t-3],_s[_t+1]]);
_s[_t+2] = closure1;
_s[_t-1] = _a;
_a = _cst21__limina;
_r = _bb27_htmlbox;
_n = 1;
_t += 2;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},6,1);

_l(_bb52_htmlbox = () => {
if (_n !== 1) {
return _w(_d);
}
_s[_t+1] = _r;
_s[_t+2] = _d;
_a = _cst21__limina;
_t += 2;
return _p(_bb53_htmlbox);
},1);

_l(_bb6_htmlbox = () => {
if (_n !== 1) {
return _w(_d);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_s[_t+3] = _d;
_a = _d(!0)[1];
_r = _bb13_htmlbox;
_t += 3;
return _p(_bb7_htmlbox);
},2);

_k(_bb27_htmlbox = () => {
_c = _s[_t-4];
_s[_t-4] = _a;
_a = _s[_t-2];
_b = _cst161__limina;
_r = _bb28_htmlbox;
_n = 3;
return _check_procedure(_s[_t-4])();
},8,1);

_j(_bb53_htmlbox = () => {
_r = _bb54_htmlbox;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_j(_bb7_htmlbox = () => {
_s[_t+1] = _a;
_s[_t+2] = _cst162__limina;
_s[_t+3] = 0;
_c = 1024;
_b = 1024;
_a = 0;
_t += 3;
return _p(_bb8_htmlbox);
});

_k(_bb13_htmlbox = () => {
_s[_t+1] = _s[_t](!0)[1];
_s[_t+2] = _cst163__limina;
_a = _cst66__limina;
_r = _bb14_htmlbox;
_n = 1;
_t += 2;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},3,1);

_k(_bb28_htmlbox = () => {
_a = _cst21__limina;
_r = _bb29_htmlbox;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},8,1);

_k(_bb54_htmlbox = () => {
_s[_t+1] = _a;
_a = _s[_t](!0)[1];
_c = !0;
_b = _cst164__limina;
_r = _s[_t-1];
++_t;
return _p(_bb55_htmlbox);
},2,1);

_j(_bb8_htmlbox = () => {
_n = 6;
return _bb9_htmlbox();
});

_k(_bb14_htmlbox = () => {
_s[_t+1] = _a;
_a = _s[_t-3];
_b = _cst165__limina;
_r = _bb15_htmlbox;
_n = 2;
return _check_procedure(_s[_t+1])();
},5,1);

_k(_bb29_htmlbox = () => {
_s[_t-4] = _a;
_a = _s[_t-6];
_c = 1024;
_b = _cst166__limina;
_r = _bb30_htmlbox;
_n = 3;
return _check_procedure(_s[_t-4])();
},8,1);

_j(_bb55_htmlbox = () => {
_n = 3;
_t -= 3;
return _check_procedure(_s[_t+3])();
});

_l(_bb9_htmlbox = () => {
if (_n === 2) {
_c = null;
} else {
if (!_build_rest(2)) {
return _w(_bb9_htmlbox);
}
}
_s[_t+1] = _a;
_s[_t+2] = _r;
_s[_t+3] = _a;
_s[_t+4] = _b;
_s[_t+5] = _c;
_a = _cst57__limina;
_t += 5;
return _p(_bb10_htmlbox);
},-1);

_k(_bb15_htmlbox = () => {
_c = 0;
_b = 0;
_r = _bb16_htmlbox;
_n = 5;
return _bb9_htmlbox();
},5,1);

_k(_bb30_htmlbox = () => {
_a = _cst21__limina;
_r = _bb31_htmlbox;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},8,1);

_k(_bb16_htmlbox = () => {
_a = _s[_t-1];
_r = _s[_t-2];
return _p(_bb17_htmlbox);
},3,1);

_k(_bb31_htmlbox = () => {
_s[_t-4] = _a;
_a = _s[_t-6];
_c = 1024;
_b = _cst167__limina;
_r = _bb32_htmlbox;
_n = 3;
return _check_procedure(_s[_t-4])();
},8,1);

_j(_bb17_htmlbox = () => {
_n = 1;
_t -= 3;
return _check_procedure(_s[_t+3](!0)[2])();
});

_k(_bb32_htmlbox = () => {
_a = _cst21__limina;
_r = _bb33_htmlbox;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},8,1);

_k(_bb33_htmlbox = () => {
_c = _s[_t-6];
_s[_t-4] = _a;
_a = _s[_t-3];
_b = _cst168__limina;
_r = _bb34_htmlbox;
_n = 3;
return _check_procedure(_s[_t-4])();
},8,1);

_k(_bb34_htmlbox = () => {
_a = _cst21__limina;
_r = _bb35_htmlbox;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},8,1);

_k(_bb35_htmlbox = () => {
_s[_t-4] = _a;
_a = _s[_t-3];
_c = !0;
_b = _cst129__limina;
_r = _bb36_htmlbox;
_n = 3;
return _check_procedure(_s[_t-4])();
},8,1);

_k(_bb36_htmlbox = () => {
var closure2 = _closure_alloc([_bb48_htmlbox,_s[_t-6],_s[_t],_s[_t-1]]);
_s[_t+1] = closure2;
_a = _cst21__limina;
_r = _bb37_htmlbox;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},8,1);

_l(_bb48_htmlbox = () => {
if (_n !== 1) {
return _w(_d);
}
_s[_t+1] = _d(!0)[3];
_s[_t+2] = _r;
_s[_t+3] = _a;
_s[_t+4] = _d;
_a = _cst169__limina;
_t += 4;
return _p(_bb49_htmlbox);
},3);

_k(_bb37_htmlbox = () => {
_c = _s[_t];
_s[_t-5] = _a;
_a = _s[_t-4];
_b = _cst171__limina;
_r = _bb38_htmlbox;
_n = 3;
_t -= 2;
return _check_procedure(_s[_t-3])();
},9,1);

_j(_bb49_htmlbox = () => {
_r = _bb50_htmlbox;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb38_htmlbox = () => {
var closure3 = _closure_alloc([_bb43_htmlbox,_s[_t-5],_s[_t-4],_s[_t]]);
_s[_t+1] = closure3;
_a = _cst21__limina;
_r = _bb39_htmlbox;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},7,1);

_k(_bb50_htmlbox = () => {
_c = _s[_t](!0)[1];
_b = _s[_t-1];
_s[_t-1] = _a;
_a = _s[_t](!0)[2];
_r = _s[_t-2];
return _p(_bb51_htmlbox);
},4,2);

_l(_bb43_htmlbox = () => {
if (_n !== 1) {
return _w(_d);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_s[_t+3] = _d;
_s[_t+4] = _d(!0)[2];
_s[_t+5] = _cst162__limina;
_s[_t+6] = 0;
_c = 1024;
_b = 1024;
_a = 0;
_t += 6;
return _p(_bb44_htmlbox);
},3);

_k(_bb39_htmlbox = () => {
_c = _s[_t];
_s[_t-6] = _a;
_a = _s[_t-3];
_b = _cst148__limina;
_r = _bb40_htmlbox;
_n = 3;
_t -= 3;
return _check_procedure(_s[_t-3])();
},8,1);

_j(_bb51_htmlbox = () => {
_n = 4;
_t -= 3;
return _check_procedure(_s[_t+2])();
});

_j(_bb44_htmlbox = () => {
_r = _bb45_htmlbox;
_n = 6;
return _bb9_htmlbox();
});

_k(_bb40_htmlbox = () => {
_a = _cst21__limina;
_r = _bb41_htmlbox;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},5,1);

_k(_bb45_htmlbox = () => {
_a = _cst172__limina;
_r = _bb46_htmlbox;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},3,1);

_k(_bb41_htmlbox = () => {
_s[_t-3] = _a;
_a = _s[_t];
_c = _cst174__limina;
_b = _cst131__limina;
_r = _bb42_htmlbox;
_n = 3;
return _check_procedure(_s[_t-3])();
},5,1);

_k(_bb46_htmlbox = () => {
_c = _s[_t](!0)[1];
_b = _s[_t-1];
_s[_t-1] = _a;
_a = _s[_t](!0)[3];
_r = _s[_t-2];
return _p(_bb47_htmlbox);
},3,1);

_k(_bb42_htmlbox = () => {
_a = _s[_t];
_t -= 5;
return _s[_t+1]();
},5,1);

_j(_bb47_htmlbox = () => {
_n = 3;
_t -= 3;
return _check_procedure(_s[_t+2])();
});



_m(_bb1_points = () => {
if (_n !== 0) {
return _w(_bb1_points);
}
_s[_t+1] = _r;
_a = _cst175__limina;
++_t;
return _p(_bb2_points);
},-1,_i("points"),!1,!0);

_j(_bb2_points = () => {
_r = _bb3_points;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_points = () => {
_r = _bb4_points;
_n = 0;
return _check_procedure(_a);
},1,1);

_k(_bb4_points = () => {
_s[_t+1] = _a;
_r = _bb5_points;
_n = 0;
++_t;
return _u(_g["[...]"],_cst177__limina)();
},1,1);

_k(_bb5_points = () => {
_s[_t+1] = _a;
_r = _bb6_points;
_n = 0;
++_t;
return _u(_g["[...]"],_cst177__limina)();
},2,1);

_k(_bb6_points = () => {
_s[_t+1] = _a;
_s[_t+2] = _s[_t-1];
_a = _cst178__limina;
_r = _bb7_points;
_n = 1;
_t += 2;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},3,1);

_k(_bb7_points = () => {
_s[_t+1] = _a;
_a = _s[_t-2];
_b = 3;
_r = _bb8_points;
_n = 2;
return _check_procedure(_s[_t+1])();
},5,1);

_k(_bb8_points = () => {
_c = _a;
_b = _cst116__limina;
_a = _g["setAttribute"];
_r = _bb23_points;
_n = 4;
return _bb10_points();
},5,1);

_l(_bb10_points = () => {
if (_n === 2) {
_c = null;
} else {
if (!_build_rest(2)) {
return _w(_bb10_points);
}
}
_s[_t+1] = _a;
_s[_t+2] = _r;
_s[_t+3] = _a;
_s[_t+4] = _b;
_s[_t+5] = _c;
_a = _cst70__limina;
_t += 5;
return _p(_bb11_points);
},-1);

_k(_bb23_points = () => {
_s[_t-1] = _s[_t-2];
_a = _cst181__limina;
_r = _bb24_points;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},4,1);

_j(_bb11_points = () => {
_r = _bb12_points;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb24_points = () => {
_s[_t+1] = _a;
_a = _s[_t];
_b = 3;
_r = _bb25_points;
_n = 2;
--_t;
return _check_procedure(_s[_t+2])();
},4,1);

_k(_bb12_points = () => {
_c = _s[_t-1];
_b = _s[_t-2];
_s[_t-2] = _a;
_a = _s[_t];
_r = _s[_t-3];
return _p(_bb13_points);
},5,2);

_k(_bb25_points = () => {
_c = _a;
_b = _cst112__limina;
_a = _g["setAttribute"];
_r = _bb26_points;
_n = 4;
return _bb10_points();
},3,1);

_j(_bb13_points = () => {
_n = 4;
_t -= 4;
return _check_procedure(_s[_t+2])();
});

_k(_bb26_points = () => {
_a = _cst183__limina;
_r = _bb27_points;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},2,1);

_k(_bb27_points = () => {
_r = _bb9_points;
_n = 0;
return _check_procedure(_a);
},2,1);

_k(_bb9_points = () => {
_c = _cst185__limina;
_b = _cst186__limina;
_r = _bb14_points;
_n = 3;
return _bb10_points();
},2,1);

_k(_bb14_points = () => {
_s[_t+1] = _a;
_a = _cst187__limina;
_r = _bb15_points;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},2,1);

_k(_bb15_points = () => {
_b = _host2scm({size: .03,
                               depthWrite: false,
                               blending: THREE.AdditiveBlending,
                               vertexColors: true,
                               transparent: true
                               });
_s[_t+1] = _a;
_a = _b;
_r = _bb16_points;
_n = 1;
return _check_procedure(_s[_t+1])();
},3,1);

_k(_bb16_points = () => {
_s[_t+1] = _a;
_a = _cst189__limina;
_r = _bb17_points;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},3,1);

_k(_bb17_points = () => {
_s[_t+1] = _a;
_a = _s[_t-2];
_b = _g["mat"];
_r = _bb18_points;
_n = 2;
return _check_procedure(_s[_t+1])();
},4,1);

_k(_bb18_points = () => {
_s[_t-2] = _a;
_a = _cst21__limina;
_r = _bb19_points;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},4,1);

_k(_bb19_points = () => {
_c = _s[_t-1];
_s[_t-1] = _a;
_a = _s[_t];
_b = _cst161__limina;
_r = _bb20_points;
_n = 3;
_t -= 2;
return _check_procedure(_s[_t+1])();
},4,1);

_k(_bb20_points = () => {
_a = _cst21__limina;
_r = _bb21_points;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},2,1);

_k(_bb21_points = () => {
_s[_t+1] = _a;
_a = _s[_t];
_c = _cst191__limina;
_b = _cst131__limina;
_r = _bb22_points;
_n = 3;
return _check_procedure(_s[_t+1])();
},2,1);

_k(_bb22_points = () => {
_a = _s[_t];
_t -= 2;
return _s[_t+1]();
},2,1);



_m(_bb1_raymarcher = () => {
if (_n !== 0) {
return _w(_bb1_raymarcher);
}
_s[_t+1] = _r;
_a = _cst192__limina;
++_t;
return _p(_bb2_raymarcher);
},-1,_i("raymarcher"),!1,!0);

_j(_bb2_raymarcher = () => {
_r = _bb3_raymarcher;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_raymarcher = () => {
_b = _host2scm({
                            conetracing: true,
                            resolution: .3,
                            blending: .2,
                            roughness: 1,
                            metalness: .8,
                            envMapIntensity: .7,
                           });
_s[_t+1] = _a;
_a = _b;
_r = _bb4_raymarcher;
_n = 1;
return _check_procedure(_s[_t+1])();
},1,1);

_k(_bb4_raymarcher = () => {
_s[_t+1] = _a;
_r = _bb5_raymarcher;
_n = 0;
++_t;
return _u(_g["gen-layers"],_cst194__limina)();
},1,1);

_k(_bb5_raymarcher = () => {
_s[_t+1] = _a;
_a = _cst21__limina;
_r = _bb6_raymarcher;
_n = 1;
++_t;
return _u(_g["##host-function-memoized"],_cst2__limina)();
},2,1);

_k(_bb6_raymarcher = () => {
_c = _s[_t];
_s[_t] = _a;
_a = _s[_t-1];
_b = _cst195__limina;
_r = _bb7_raymarcher;
_n = 3;
--_t;
return _check_procedure(_s[_t+1])();
},3,1);

_k(_bb7_raymarcher = () => {
_a = _s[_t];
_t -= 2;
return _s[_t+1]();
},2,1);



_m(_bb1_register_2d_fn = () => {
if (_n !== 2) {
return _w(_bb1_register_2d_fn);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_s[_t+3] = _b;
_a = _cst7__limina;
_t += 3;
return _p(_bb2_register_2d_fn);
},-1,_i("register-fn"),!1,!0);

_j(_bb2_register_2d_fn = () => {
_r = _bb3_register_2d_fn;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_register_2d_fn = () => {
_b = _s[_t];
_s[_t] = _a;
_a = _s[_t-1];
_r = _s[_t-2];
return _p(_bb4_register_2d_fn);
},3,1);

_j(_bb4_register_2d_fn = () => {
_n = 2;
_t -= 3;
return _check_procedure(_s[_t+3])();
});



_m(_bb1_scm2host_2d_expression = () => {
if (_n !== 1) {
return _w(_bb1_scm2host_2d_expression);
}
_a = _scm2host(_a);
return _r;
},-1,_i("scm2host-expression"),!1,!0);



_m(_bb1_host2scm_2d_expression = () => {
if (_n !== 1) {
return _w(_bb1_host2scm_2d_expression);
}
_a = _host2scm(_a);
return _r;
},-1,_i("host2scm-expression"),!1,!0);



_m(_bb1_scene = () => {
if (_n !== 0) {
return _w(_bb1_scene);
}
_s[_t+1] = _r;
_a = _cst66__limina;
++_t;
return _p(_bb2_scene);
},-1,_i("scene"),!1,!0);

_j(_bb2_scene = () => {
_r = _bb3_scene;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_scene = () => {
_b = _cst196__limina;
_s[_t+1] = _a;
_a = _g["lim"];
_r = _s[_t];
++_t;
return _p(_bb4_scene);
},1,1);

_j(_bb4_scene = () => {
_n = 2;
_t -= 2;
return _check_procedure(_s[_t+2])();
});



_m(_bb1_scene_2d_add = () => {
if (_n !== 1) {
return _w(_bb1_scene_2d_add);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_a = _cst66__limina;
_t += 2;
return _p(_bb2_scene_2d_add);
},-1,_i("scene-add"),!1,!0);

_j(_bb2_scene_2d_add = () => {
_r = _bb3_scene_2d_add;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_scene_2d_add = () => {
_b = _cst196__limina;
_s[_t+1] = _a;
_a = _g["lim"];
_r = _bb4_scene_2d_add;
_n = 2;
return _check_procedure(_s[_t+1])();
},2,1);

_k(_bb4_scene_2d_add = () => {
_c = _s[_t];
_b = _cst197__limina;
_r = _s[_t-1];
return _p(_bb5_scene_2d_add);
},2,1);

_j(_bb5_scene_2d_add = () => {
_n = 3;
_t -= 2;
return _bb6_scene_2d_add();
});

_l(_bb6_scene_2d_add = () => {
if (_n === 2) {
_c = null;
} else {
if (!_build_rest(2)) {
return _w(_bb6_scene_2d_add);
}
}
_s[_t+1] = _a;
_s[_t+2] = _r;
_s[_t+3] = _a;
_s[_t+4] = _b;
_s[_t+5] = _c;
_a = _cst70__limina;
_t += 5;
return _p(_bb7_scene_2d_add);
},-1);

_j(_bb7_scene_2d_add = () => {
_r = _bb8_scene_2d_add;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb8_scene_2d_add = () => {
_c = _s[_t-1];
_b = _s[_t-2];
_s[_t-2] = _a;
_a = _s[_t];
_r = _s[_t-3];
return _p(_bb9_scene_2d_add);
},5,2);

_j(_bb9_scene_2d_add = () => {
_n = 4;
_t -= 4;
return _check_procedure(_s[_t+2])();
});



_m(_bb1_composer = () => {
if (_n !== 1) {
return _w(_bb1_composer);
}
if (!(_a === !1)) {
return _bb2_composer();
} else {
return _bb9_composer();
}
},-1,_i("composer"),!1,!0);

_j(_bb2_composer = () => {
_s[_t+1] = _r;
_b = _cst198__limina;
_a = _g["lim"];
++_t;
return _p(_bb3_composer);
});

_j(_bb9_composer = () => {
_a = 0;
return _bb10_composer();
});

_j(_bb3_composer = () => {
_r = _bb8_composer;
_n = 2;
return _bb4_composer();
});

_j(_bb10_composer = () => {
_s[_t+1] = _r;
_s[_t+2] = _a;
_a = _cst21__limina;
_t += 2;
return _p(_bb11_composer);
});

_l(_bb4_composer = () => {
if (_n === 2) {
_c = null;
} else {
if (!_build_rest(2)) {
return _w(_bb4_composer);
}
}
_s[_t+1] = _a;
_s[_t+2] = _r;
_s[_t+3] = _a;
_s[_t+4] = _b;
_s[_t+5] = _c;
_a = _cst70__limina;
_t += 5;
return _p(_bb5_composer);
},-1);

_k(_bb8_composer = () => {
_r = _s[_t];
--_t;
return _bb10_composer();
},1,1);

_j(_bb11_composer = () => {
_r = _bb12_composer;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_j(_bb5_composer = () => {
_r = _bb6_composer;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb12_composer = () => {
_c = _s[_t];
_b = _cst199__limina;
_s[_t] = _a;
_a = _g["lim"];
_r = _s[_t-1];
return _p(_bb13_composer);
},2,1);

_k(_bb6_composer = () => {
_c = _s[_t-1];
_b = _s[_t-2];
_s[_t-2] = _a;
_a = _s[_t];
_r = _s[_t-3];
return _p(_bb7_composer);
},5,2);

_j(_bb13_composer = () => {
_n = 3;
_t -= 2;
return _check_procedure(_s[_t+2])();
});

_j(_bb7_composer = () => {
_n = 4;
_t -= 4;
return _check_procedure(_s[_t+2])();
});



_m(_bb1_obj = () => {
if (_n !== 1) {
return _w(_bb1_obj);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_a = _cst200__limina;
_t += 2;
return _p(_bb2_obj);
},-1,_i("obj"),!1,!0);

_j(_bb2_obj = () => {
_r = _bb3_obj;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_obj = () => {
_s[_t+1] = _a;
_a = _s[_t];
_r = _s[_t-1];
++_t;
return _p(_bb4_obj);
},2,1);

_j(_bb4_obj = () => {
_n = 1;
_t -= 3;
return _check_procedure(_s[_t+3])();
});



_m(_bb1_objs = () => {
if (_n !== 1) {
return _w(_bb1_objs);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_a = _cst202__limina;
_t += 2;
return _p(_bb2_objs);
},-1,_i("objs"),!1,!0);

_j(_bb2_objs = () => {
_r = _bb3_objs;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_objs = () => {
_s[_t+1] = _a;
_a = _s[_t];
_r = _s[_t-1];
++_t;
return _p(_bb4_objs);
},2,1);

_j(_bb4_objs = () => {
_n = 1;
_t -= 3;
return _check_procedure(_s[_t+3])();
});



_m(_bb1_timo0 = () => {
if (_n !== 1) {
return _w(_bb1_timo0);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_a = _cst204__limina;
_t += 2;
return _p(_bb2_timo0);
},-1,_i("timo0"),!1,!0);

_j(_bb2_timo0 = () => {
_r = _bb3_timo0;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_timo0 = () => {
_s[_t+1] = _a;
_a = _s[_t];
_r = _s[_t-1];
++_t;
return _p(_bb4_timo0);
},2,1);

_j(_bb4_timo0 = () => {
_n = 1;
_t -= 3;
return _check_procedure(_s[_t+3])();
});



_m(_bb1_timo = () => {
if (_n !== 1) {
return _w(_bb1_timo);
}
_s[_t+1] = _r;
_s[_t+2] = _a;
_a = _cst206__limina;
_t += 2;
return _p(_bb2_timo);
},-1,_i("timo"),!1,!0);

_j(_bb2_timo = () => {
_r = _bb3_timo;
_n = 1;
return _u(_g["##host-function-memoized"],_cst2__limina)();
});

_k(_bb3_timo = () => {
_s[_t+1] = _a;
_a = _s[_t];
_r = _s[_t-1];
++_t;
return _p(_bb4_timo);
},2,1);

_j(_bb4_timo = () => {
_n = 1;
_t -= 3;
return _check_procedure(_s[_t+3])();
});



_module_register([[_i("limina")],[_i("_six/js"),_i("srfi/1"),_i("srfi/69")],null,1,_bb1_limina_23_,!1]);

