// File generated by Gambit v4.9.4
// Link info: (409004 (js ((compactness 9))) "macros" (("macros")) (module_register parententrypt_init make_interned_symbol r0 r1 wrong_nargs nargs) () () () #f)

_m(_bb1_macros_23_ = () => {
if (_n !== 0) {
return _w(_bb1_macros_23_);
}
_a = !1;
return _r;
},-1,_i("macros#"),!1,!0);



_module_register([[_i("macros")],[],null,1,_bb1_macros_23_,!1]);

